/********************************************************************
* src/root/TADCClassDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error src/root/TADCClassDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableTADCClassDict();
extern void G__cpp_setup_inheritanceTADCClassDict();
extern void G__cpp_setup_typetableTADCClassDict();
extern void G__cpp_setup_memvarTADCClassDict();
extern void G__cpp_setup_globalTADCClassDict();
extern void G__cpp_setup_memfuncTADCClassDict();
extern void G__cpp_setup_funcTADCClassDict();
extern void G__set_cpp_environmentTADCClassDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "src/root/TADCClass.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__TADCClassDictLN_TClass;
extern G__linked_taginfo G__TADCClassDictLN_TBuffer;
extern G__linked_taginfo G__TADCClassDictLN_TMemberInspector;
extern G__linked_taginfo G__TADCClassDictLN_TObject;
extern G__linked_taginfo G__TADCClassDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__TADCClassDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TADCClassDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__TADCClassDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TADCClassDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__TADCClassDictLN_TArrayS;
extern G__linked_taginfo G__TADCClassDictLN_TADCClass;

/* STUB derived class for protected member access */
