//
// File generated by /opt/local/libexec/root5/bin/rootcint at Thu Oct  2 15:57:17 2014

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME srcdIrootdITClas12ReaderDict
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "TClas12ReaderDict.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TInterpreter.h"
#include "TVirtualMutex.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// Direct notice to TROOT of the dictionary's loading.
namespace {
   static struct DictInit {
      DictInit() {
         ROOT::RegisterModule();
      }
   } __TheDictionaryInitializer;
}

// START OF SHADOWS

namespace ROOT {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOT
// END OF SHADOWS

namespace ROOT {
   void TClas12Reader_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void TClas12Reader_Dictionary();
   static void *new_TClas12Reader(void *p = 0);
   static void *newArray_TClas12Reader(Long_t size, void *p);
   static void delete_TClas12Reader(void *p);
   static void deleteArray_TClas12Reader(void *p);
   static void destruct_TClas12Reader(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::TClas12Reader*)
   {
      ::TClas12Reader *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(::TClas12Reader),0);
      static ::ROOT::TGenericClassInfo 
         instance("TClas12Reader", "./src/root/TClas12Reader.h", 22,
                  typeid(::TClas12Reader), DefineBehavior(ptr, ptr),
                  0, &TClas12Reader_Dictionary, isa_proxy, 0,
                  sizeof(::TClas12Reader) );
      instance.SetNew(&new_TClas12Reader);
      instance.SetNewArray(&newArray_TClas12Reader);
      instance.SetDelete(&delete_TClas12Reader);
      instance.SetDeleteArray(&deleteArray_TClas12Reader);
      instance.SetDestructor(&destruct_TClas12Reader);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::TClas12Reader*)
   {
      return GenerateInitInstanceLocal((::TClas12Reader*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::TClas12Reader*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void TClas12Reader_Dictionary() {
      ::ROOT::GenerateInitInstanceLocal((const ::TClas12Reader*)0x0)->GetClass();
   }

} // end of namespace ROOT

namespace ROOT {
   // Wrappers around operator new
   static void *new_TClas12Reader(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) ::TClas12Reader : new ::TClas12Reader;
   }
   static void *newArray_TClas12Reader(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) ::TClas12Reader[nElements] : new ::TClas12Reader[nElements];
   }
   // Wrapper around operator delete
   static void delete_TClas12Reader(void *p) {
      delete ((::TClas12Reader*)p);
   }
   static void deleteArray_TClas12Reader(void *p) {
      delete [] ((::TClas12Reader*)p);
   }
   static void destruct_TClas12Reader(void *p) {
      typedef ::TClas12Reader current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class ::TClas12Reader

/********************************************************
* src/root/TClas12ReaderDict.cc
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtableTClas12ReaderDict();

extern "C" void G__set_cpp_environmentTClas12ReaderDict() {
  G__cpp_reset_tagtableTClas12ReaderDict();
}
#include <new>
extern "C" int G__cpp_dllrevTClas12ReaderDict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* TClas12Reader */
static int G__TClas12ReaderDict_605_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   TClas12Reader* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new TClas12Reader[n];
     } else {
       p = new((void*) gvp) TClas12Reader[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new TClas12Reader;
     } else {
       p = new((void*) gvp) TClas12Reader;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__TClas12ReaderDictLN_TClas12Reader));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TClas12ReaderDict_605_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TClas12Reader*) G__getstructoffset())->addFile((const char*) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TClas12ReaderDict_605_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TClas12Reader*) G__getstructoffset())->open();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TClas12ReaderDict_605_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((TClas12Reader*) G__getstructoffset())->next());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TClas12ReaderDict_605_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((TClas12Reader*) G__getstructoffset())->getGeneratedEvent());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TClas12ReaderDict_605_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((TClas12Reader*) G__getstructoffset())->getEvent());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__TClas12ReaderDict_605_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   TClas12Reader* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new TClas12Reader(*(TClas12Reader*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__TClas12ReaderDictLN_TClas12Reader));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef TClas12Reader G__TTClas12Reader;
static int G__TClas12ReaderDict_605_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 0
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (TClas12Reader*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((TClas12Reader*) (soff+(sizeof(TClas12Reader)*i)))->~G__TTClas12Reader();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (TClas12Reader*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((TClas12Reader*) (soff))->~G__TTClas12Reader();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* TClas12Reader */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncTClas12ReaderDict {
 public:
  G__Sizep2memfuncTClas12ReaderDict(): p(&G__Sizep2memfuncTClas12ReaderDict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncTClas12ReaderDict::*p)();
};

size_t G__get_sizep2memfuncTClas12ReaderDict()
{
  G__Sizep2memfuncTClas12ReaderDict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceTClas12ReaderDict() {

   /* Setting up class inheritance */
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableTClas12ReaderDict() {

   /* Setting up typedef entry */
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__TClas12ReaderDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__TClas12ReaderDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__TClas12ReaderDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__TClas12ReaderDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__TClas12ReaderDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__TClas12ReaderDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__TClas12ReaderDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__TClas12ReaderDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__TClas12ReaderDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__TClas12ReaderDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<std::bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__TClas12ReaderDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__TClas12ReaderDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*>",117,G__get_linked_tagnum(&G__TClas12ReaderDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long>",117,G__get_linked_tagnum(&G__TClas12ReaderDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long,const TObject**>",117,G__get_linked_tagnum(&G__TClas12ReaderDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Float_t>",117,G__get_linked_tagnum(&G__TClas12ReaderDictLN_TMatrixTBaselEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Double_t>",117,G__get_linked_tagnum(&G__TClas12ReaderDictLN_TMatrixTBaselEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Float_t>",117,G__get_linked_tagnum(&G__TClas12ReaderDictLN_TVectorTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Double_t>",117,G__get_linked_tagnum(&G__TClas12ReaderDictLN_TVectorTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixT<Float_t>",117,G__get_linked_tagnum(&G__TClas12ReaderDictLN_TMatrixTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTRow_const<Float_t>",117,G__get_linked_tagnum(&G__TClas12ReaderDictLN_TMatrixTRow_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTColumn_const<Float_t>",117,G__get_linked_tagnum(&G__TClas12ReaderDictLN_TMatrixTColumn_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTDiag_const<Float_t>",117,G__get_linked_tagnum(&G__TClas12ReaderDictLN_TMatrixTDiag_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTFlat_const<Float_t>",117,G__get_linked_tagnum(&G__TClas12ReaderDictLN_TMatrixTFlat_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSub_const<Float_t>",117,G__get_linked_tagnum(&G__TClas12ReaderDictLN_TMatrixTSub_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseRow_const<Float_t>",117,G__get_linked_tagnum(&G__TClas12ReaderDictLN_TMatrixTSparseRow_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseDiag_const<Float_t>",117,G__get_linked_tagnum(&G__TClas12ReaderDictLN_TMatrixTSparseDiag_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTRow<Float_t>",117,G__get_linked_tagnum(&G__TClas12ReaderDictLN_TMatrixTRowlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTColumn<Float_t>",117,G__get_linked_tagnum(&G__TClas12ReaderDictLN_TMatrixTColumnlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTDiag<Float_t>",117,G__get_linked_tagnum(&G__TClas12ReaderDictLN_TMatrixTDiaglEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTFlat<Float_t>",117,G__get_linked_tagnum(&G__TClas12ReaderDictLN_TMatrixTFlatlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSub<Float_t>",117,G__get_linked_tagnum(&G__TClas12ReaderDictLN_TMatrixTSublEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseRow<Float_t>",117,G__get_linked_tagnum(&G__TClas12ReaderDictLN_TMatrixTSparseRowlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseDiag<Float_t>",117,G__get_linked_tagnum(&G__TClas12ReaderDictLN_TMatrixTSparseDiaglEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TElementActionT<Float_t>",117,G__get_linked_tagnum(&G__TClas12ReaderDictLN_TElementActionTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TElementPosActionT<Float_t>",117,G__get_linked_tagnum(&G__TClas12ReaderDictLN_TElementPosActionTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<int>",117,G__get_linked_tagnum(&G__TClas12ReaderDictLN_vectorlEintcOallocatorlEintgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__TClas12ReaderDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__TClas12ReaderDictLN_vectorlEintcOallocatorlEintgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__TClas12ReaderDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__TClas12ReaderDictLN_vectorlEintcOallocatorlEintgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<string>",117,G__get_linked_tagnum(&G__TClas12ReaderDictLN_vectorlEstringcOallocatorlEstringgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__TClas12ReaderDictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__TClas12ReaderDictLN_vectorlEstringcOallocatorlEstringgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__TClas12ReaderDictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__TClas12ReaderDictLN_vectorlEstringcOallocatorlEstringgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<DescriptorEntry_t>",117,G__get_linked_tagnum(&G__TClas12ReaderDictLN_vectorlEDescriptorEntry_tcOallocatorlEDescriptorEntry_tgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__TClas12ReaderDictLN_reverse_iteratorlEvectorlEDescriptorEntry_tcOallocatorlEDescriptorEntry_tgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__TClas12ReaderDictLN_vectorlEDescriptorEntry_tcOallocatorlEDescriptorEntry_tgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__TClas12ReaderDictLN_reverse_iteratorlEvectorlEDescriptorEntry_tcOallocatorlEDescriptorEntry_tgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__TClas12ReaderDictLN_vectorlEDescriptorEntry_tcOallocatorlEDescriptorEntry_tgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<int,vector<double> >",117,G__get_linked_tagnum(&G__TClas12ReaderDictLN_maplEintcOvectorlEdoublecOallocatorlEdoublegRsPgRcOlesslEintgRcOallocatorlEpairlEconstsPintcOvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<int,vector<double,allocator<double> > >",117,G__get_linked_tagnum(&G__TClas12ReaderDictLN_maplEintcOvectorlEdoublecOallocatorlEdoublegRsPgRcOlesslEintgRcOallocatorlEpairlEconstsPintcOvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<int,vector<double,allocator<double> >,less<int> >",117,G__get_linked_tagnum(&G__TClas12ReaderDictLN_maplEintcOvectorlEdoublecOallocatorlEdoublegRsPgRcOlesslEintgRcOallocatorlEpairlEconstsPintcOvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<int32_t>",117,G__get_linked_tagnum(&G__TClas12ReaderDictLN_vectorlEintcOallocatorlEintgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<int,vector<int32_t> >",117,G__get_linked_tagnum(&G__TClas12ReaderDictLN_maplEintcOvectorlEintcOallocatorlEintgRsPgRcOlesslEintgRcOallocatorlEpairlEconstsPintcOvectorlEintcOallocatorlEintgRsPgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<int,vector<int,allocator<int> > >",117,G__get_linked_tagnum(&G__TClas12ReaderDictLN_maplEintcOvectorlEintcOallocatorlEintgRsPgRcOlesslEintgRcOallocatorlEpairlEconstsPintcOvectorlEintcOallocatorlEintgRsPgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<int,vector<int,allocator<int> >,less<int> >",117,G__get_linked_tagnum(&G__TClas12ReaderDictLN_maplEintcOvectorlEintcOallocatorlEintgRsPgRcOlesslEintgRcOallocatorlEpairlEconstsPintcOvectorlEintcOallocatorlEintgRsPgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<CompositeADC_t>",117,G__get_linked_tagnum(&G__TClas12ReaderDictLN_vectorlECompositeADC_tcOallocatorlECompositeADC_tgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__TClas12ReaderDictLN_reverse_iteratorlEvectorlECompositeADC_tcOallocatorlECompositeADC_tgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__TClas12ReaderDictLN_vectorlECompositeADC_tcOallocatorlECompositeADC_tgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__TClas12ReaderDictLN_reverse_iteratorlEvectorlECompositeADC_tcOallocatorlECompositeADC_tgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__TClas12ReaderDictLN_vectorlECompositeADC_tcOallocatorlECompositeADC_tgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<uint32_t>",117,G__get_linked_tagnum(&G__TClas12ReaderDictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<uint32_t,bankIndex_t>",117,G__get_linked_tagnum(&G__TClas12ReaderDictLN_maplEunsignedsPintcObankIndex_tcOlesslEunsignedsPintgRcOallocatorlEpairlEconstsPunsignedsPintcObankIndex_tgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<unsigned int,bankIndex_t>",117,G__get_linked_tagnum(&G__TClas12ReaderDictLN_maplEunsignedsPintcObankIndex_tcOlesslEunsignedsPintgRcOallocatorlEpairlEconstsPunsignedsPintcObankIndex_tgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<unsigned int,bankIndex_t,less<unsigned int> >",117,G__get_linked_tagnum(&G__TClas12ReaderDictLN_maplEunsignedsPintcObankIndex_tcOlesslEunsignedsPintgRcOallocatorlEpairlEconstsPunsignedsPintcObankIndex_tgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<uint8_t>",117,G__get_linked_tagnum(&G__TClas12ReaderDictLN_vectorlEunsignedsPcharcOallocatorlEunsignedsPchargRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<UInt_t>",117,G__get_linked_tagnum(&G__TClas12ReaderDictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TString>",117,G__get_linked_tagnum(&G__TClas12ReaderDictLN_vectorlETStringcOallocatorlETStringgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__TClas12ReaderDictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__TClas12ReaderDictLN_vectorlETStringcOallocatorlETStringgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__TClas12ReaderDictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__TClas12ReaderDictLN_vectorlETStringcOallocatorlETStringgRsPgR));
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* TClas12Reader */
static void G__setup_memvarTClas12Reader(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__TClas12ReaderDictLN_TClas12Reader));
   { TClas12Reader *p; p=(TClas12Reader*)0x1000; if (p) { }
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__TClas12ReaderDictLN_vectorlEstringcOallocatorlEstringgRsPgR),G__defined_typename("vector<string>"),-1,4,"files=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__TClas12ReaderDictLN_TEvioFileReader),-1,-1,4,"reader=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__TClas12ReaderDictLN_TEvioDataEvent),-1,-1,4,"event=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarTClas12ReaderDict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncTClas12Reader(void) {
   /* TClas12Reader */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__TClas12ReaderDictLN_TClas12Reader));
   G__memfunc_setup("TClas12Reader",1165,G__TClas12ReaderDict_605_0_1, 105, G__get_linked_tagnum(&G__TClas12ReaderDictLN_TClas12Reader), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("addFile",681,G__TClas12ReaderDict_605_0_2, 121, -1, -1, 0, 1, 1, 1, 0, "C - - 10 - file", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("open",434,G__TClas12ReaderDict_605_0_3, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("next",447,G__TClas12ReaderDict_605_0_4, 103, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("getGeneratedEvent",1745,G__TClas12ReaderDict_605_0_5, 85, G__get_linked_tagnum(&G__TClas12ReaderDictLN_TPhysicsEvent), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("getEvent",834,G__TClas12ReaderDict_605_0_6, 85, G__get_linked_tagnum(&G__TClas12ReaderDictLN_TPhysicsEvent), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   // automatic copy constructor
   G__memfunc_setup("TClas12Reader", 1165, G__TClas12ReaderDict_605_0_7, (int) ('i'), G__get_linked_tagnum(&G__TClas12ReaderDictLN_TClas12Reader), -1, 0, 1, 1, 1, 0, "u 'TClas12Reader' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~TClas12Reader", 1291, G__TClas12ReaderDict_605_0_8, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncTClas12ReaderDict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
}

static void G__cpp_setup_global2() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalTClas12ReaderDict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {
}

static void G__cpp_setup_func16() {
}

static void G__cpp_setup_func17() {
}

static void G__cpp_setup_func18() {
}

static void G__cpp_setup_func19() {
}

static void G__cpp_setup_func20() {
}

static void G__cpp_setup_func21() {
}

static void G__cpp_setup_func22() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcTClas12ReaderDict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
  G__cpp_setup_func16();
  G__cpp_setup_func17();
  G__cpp_setup_func18();
  G__cpp_setup_func19();
  G__cpp_setup_func20();
  G__cpp_setup_func21();
  G__cpp_setup_func22();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__TClas12ReaderDictLN_vectorlEunsignedsPcharcOallocatorlEunsignedsPchargRsPgR = { "vector<unsigned char,allocator<unsigned char> >" , 99 , -1 };
G__linked_taginfo G__TClas12ReaderDictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR = { "vector<unsigned int,allocator<unsigned int> >" , 99 , -1 };
G__linked_taginfo G__TClas12ReaderDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__TClas12ReaderDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__TClas12ReaderDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__TClas12ReaderDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__TClas12ReaderDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR = { "iterator<bidirectional_iterator_tag,TObject*,long,const TObject**,const TObject*&>" , 115 , -1 };
G__linked_taginfo G__TClas12ReaderDictLN_TMatrixTBaselEfloatgR = { "TMatrixTBase<float>" , 99 , -1 };
G__linked_taginfo G__TClas12ReaderDictLN_TMatrixTBaselEdoublegR = { "TMatrixTBase<double>" , 99 , -1 };
G__linked_taginfo G__TClas12ReaderDictLN_TVectorTlEfloatgR = { "TVectorT<float>" , 99 , -1 };
G__linked_taginfo G__TClas12ReaderDictLN_TVectorTlEdoublegR = { "TVectorT<double>" , 99 , -1 };
G__linked_taginfo G__TClas12ReaderDictLN_TElementActionTlEfloatgR = { "TElementActionT<float>" , 99 , -1 };
G__linked_taginfo G__TClas12ReaderDictLN_TElementPosActionTlEfloatgR = { "TElementPosActionT<float>" , 99 , -1 };
G__linked_taginfo G__TClas12ReaderDictLN_TMatrixTlEfloatgR = { "TMatrixT<float>" , 99 , -1 };
G__linked_taginfo G__TClas12ReaderDictLN_TMatrixTRow_constlEfloatgR = { "TMatrixTRow_const<float>" , 99 , -1 };
G__linked_taginfo G__TClas12ReaderDictLN_TMatrixTRowlEfloatgR = { "TMatrixTRow<float>" , 99 , -1 };
G__linked_taginfo G__TClas12ReaderDictLN_TMatrixTDiag_constlEfloatgR = { "TMatrixTDiag_const<float>" , 99 , -1 };
G__linked_taginfo G__TClas12ReaderDictLN_TMatrixTColumn_constlEfloatgR = { "TMatrixTColumn_const<float>" , 99 , -1 };
G__linked_taginfo G__TClas12ReaderDictLN_TMatrixTFlat_constlEfloatgR = { "TMatrixTFlat_const<float>" , 99 , -1 };
G__linked_taginfo G__TClas12ReaderDictLN_TMatrixTSub_constlEfloatgR = { "TMatrixTSub_const<float>" , 99 , -1 };
G__linked_taginfo G__TClas12ReaderDictLN_TMatrixTSparseRow_constlEfloatgR = { "TMatrixTSparseRow_const<float>" , 99 , -1 };
G__linked_taginfo G__TClas12ReaderDictLN_TMatrixTSparseDiag_constlEfloatgR = { "TMatrixTSparseDiag_const<float>" , 99 , -1 };
G__linked_taginfo G__TClas12ReaderDictLN_TMatrixTColumnlEfloatgR = { "TMatrixTColumn<float>" , 99 , -1 };
G__linked_taginfo G__TClas12ReaderDictLN_TMatrixTDiaglEfloatgR = { "TMatrixTDiag<float>" , 99 , -1 };
G__linked_taginfo G__TClas12ReaderDictLN_TMatrixTFlatlEfloatgR = { "TMatrixTFlat<float>" , 99 , -1 };
G__linked_taginfo G__TClas12ReaderDictLN_TMatrixTSublEfloatgR = { "TMatrixTSub<float>" , 99 , -1 };
G__linked_taginfo G__TClas12ReaderDictLN_TMatrixTSparseRowlEfloatgR = { "TMatrixTSparseRow<float>" , 99 , -1 };
G__linked_taginfo G__TClas12ReaderDictLN_TMatrixTSparseDiaglEfloatgR = { "TMatrixTSparseDiag<float>" , 99 , -1 };
G__linked_taginfo G__TClas12ReaderDictLN_vectorlEintcOallocatorlEintgRsPgR = { "vector<int,allocator<int> >" , 99 , -1 };
G__linked_taginfo G__TClas12ReaderDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<int,allocator<int> >::iterator>" , 99 , -1 };
G__linked_taginfo G__TClas12ReaderDictLN_vectorlEstringcOallocatorlEstringgRsPgR = { "vector<string,allocator<string> >" , 99 , -1 };
G__linked_taginfo G__TClas12ReaderDictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<string,allocator<string> >::iterator>" , 99 , -1 };
G__linked_taginfo G__TClas12ReaderDictLN_TPhysicsEvent = { "TPhysicsEvent" , 99 , -1 };
G__linked_taginfo G__TClas12ReaderDictLN_vectorlEDescriptorEntry_tcOallocatorlEDescriptorEntry_tgRsPgR = { "vector<DescriptorEntry_t,allocator<DescriptorEntry_t> >" , 99 , -1 };
G__linked_taginfo G__TClas12ReaderDictLN_reverse_iteratorlEvectorlEDescriptorEntry_tcOallocatorlEDescriptorEntry_tgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<DescriptorEntry_t,allocator<DescriptorEntry_t> >::iterator>" , 99 , -1 };
G__linked_taginfo G__TClas12ReaderDictLN_maplEintcOvectorlEdoublecOallocatorlEdoublegRsPgRcOlesslEintgRcOallocatorlEpairlEconstsPintcOvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRsPgR = { "map<int,vector<double,allocator<double> >,less<int>,allocator<pair<const int,vector<double,allocator<double> > > > >" , 99 , -1 };
G__linked_taginfo G__TClas12ReaderDictLN_maplEintcOvectorlEintcOallocatorlEintgRsPgRcOlesslEintgRcOallocatorlEpairlEconstsPintcOvectorlEintcOallocatorlEintgRsPgRsPgRsPgRsPgR = { "map<int,vector<int,allocator<int> >,less<int>,allocator<pair<const int,vector<int,allocator<int> > > > >" , 99 , -1 };
G__linked_taginfo G__TClas12ReaderDictLN_vectorlECompositeADC_tcOallocatorlECompositeADC_tgRsPgR = { "vector<CompositeADC_t,allocator<CompositeADC_t> >" , 99 , -1 };
G__linked_taginfo G__TClas12ReaderDictLN_reverse_iteratorlEvectorlECompositeADC_tcOallocatorlECompositeADC_tgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<CompositeADC_t,allocator<CompositeADC_t> >::iterator>" , 99 , -1 };
G__linked_taginfo G__TClas12ReaderDictLN_maplEunsignedsPintcObankIndex_tcOlesslEunsignedsPintgRcOallocatorlEpairlEconstsPunsignedsPintcObankIndex_tgRsPgRsPgR = { "map<unsigned int,bankIndex_t,less<unsigned int>,allocator<pair<const unsigned int,bankIndex_t> > >" , 99 , -1 };
G__linked_taginfo G__TClas12ReaderDictLN_vectorlETStringcOallocatorlETStringgRsPgR = { "vector<TString,allocator<TString> >" , 99 , -1 };
G__linked_taginfo G__TClas12ReaderDictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TString,allocator<TString> >::iterator>" , 99 , -1 };
G__linked_taginfo G__TClas12ReaderDictLN_TEvioDataEvent = { "TEvioDataEvent" , 99 , -1 };
G__linked_taginfo G__TClas12ReaderDictLN_TEvioFileReader = { "TEvioFileReader" , 99 , -1 };
G__linked_taginfo G__TClas12ReaderDictLN_TClas12Reader = { "TClas12Reader" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableTClas12ReaderDict() {
  G__TClas12ReaderDictLN_vectorlEunsignedsPcharcOallocatorlEunsignedsPchargRsPgR.tagnum = -1 ;
  G__TClas12ReaderDictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR.tagnum = -1 ;
  G__TClas12ReaderDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__TClas12ReaderDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__TClas12ReaderDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__TClas12ReaderDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__TClas12ReaderDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR.tagnum = -1 ;
  G__TClas12ReaderDictLN_TMatrixTBaselEfloatgR.tagnum = -1 ;
  G__TClas12ReaderDictLN_TMatrixTBaselEdoublegR.tagnum = -1 ;
  G__TClas12ReaderDictLN_TVectorTlEfloatgR.tagnum = -1 ;
  G__TClas12ReaderDictLN_TVectorTlEdoublegR.tagnum = -1 ;
  G__TClas12ReaderDictLN_TElementActionTlEfloatgR.tagnum = -1 ;
  G__TClas12ReaderDictLN_TElementPosActionTlEfloatgR.tagnum = -1 ;
  G__TClas12ReaderDictLN_TMatrixTlEfloatgR.tagnum = -1 ;
  G__TClas12ReaderDictLN_TMatrixTRow_constlEfloatgR.tagnum = -1 ;
  G__TClas12ReaderDictLN_TMatrixTRowlEfloatgR.tagnum = -1 ;
  G__TClas12ReaderDictLN_TMatrixTDiag_constlEfloatgR.tagnum = -1 ;
  G__TClas12ReaderDictLN_TMatrixTColumn_constlEfloatgR.tagnum = -1 ;
  G__TClas12ReaderDictLN_TMatrixTFlat_constlEfloatgR.tagnum = -1 ;
  G__TClas12ReaderDictLN_TMatrixTSub_constlEfloatgR.tagnum = -1 ;
  G__TClas12ReaderDictLN_TMatrixTSparseRow_constlEfloatgR.tagnum = -1 ;
  G__TClas12ReaderDictLN_TMatrixTSparseDiag_constlEfloatgR.tagnum = -1 ;
  G__TClas12ReaderDictLN_TMatrixTColumnlEfloatgR.tagnum = -1 ;
  G__TClas12ReaderDictLN_TMatrixTDiaglEfloatgR.tagnum = -1 ;
  G__TClas12ReaderDictLN_TMatrixTFlatlEfloatgR.tagnum = -1 ;
  G__TClas12ReaderDictLN_TMatrixTSublEfloatgR.tagnum = -1 ;
  G__TClas12ReaderDictLN_TMatrixTSparseRowlEfloatgR.tagnum = -1 ;
  G__TClas12ReaderDictLN_TMatrixTSparseDiaglEfloatgR.tagnum = -1 ;
  G__TClas12ReaderDictLN_vectorlEintcOallocatorlEintgRsPgR.tagnum = -1 ;
  G__TClas12ReaderDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__TClas12ReaderDictLN_vectorlEstringcOallocatorlEstringgRsPgR.tagnum = -1 ;
  G__TClas12ReaderDictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__TClas12ReaderDictLN_TPhysicsEvent.tagnum = -1 ;
  G__TClas12ReaderDictLN_vectorlEDescriptorEntry_tcOallocatorlEDescriptorEntry_tgRsPgR.tagnum = -1 ;
  G__TClas12ReaderDictLN_reverse_iteratorlEvectorlEDescriptorEntry_tcOallocatorlEDescriptorEntry_tgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__TClas12ReaderDictLN_maplEintcOvectorlEdoublecOallocatorlEdoublegRsPgRcOlesslEintgRcOallocatorlEpairlEconstsPintcOvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRsPgR.tagnum = -1 ;
  G__TClas12ReaderDictLN_maplEintcOvectorlEintcOallocatorlEintgRsPgRcOlesslEintgRcOallocatorlEpairlEconstsPintcOvectorlEintcOallocatorlEintgRsPgRsPgRsPgRsPgR.tagnum = -1 ;
  G__TClas12ReaderDictLN_vectorlECompositeADC_tcOallocatorlECompositeADC_tgRsPgR.tagnum = -1 ;
  G__TClas12ReaderDictLN_reverse_iteratorlEvectorlECompositeADC_tcOallocatorlECompositeADC_tgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__TClas12ReaderDictLN_maplEunsignedsPintcObankIndex_tcOlesslEunsignedsPintgRcOallocatorlEpairlEconstsPunsignedsPintcObankIndex_tgRsPgRsPgR.tagnum = -1 ;
  G__TClas12ReaderDictLN_vectorlETStringcOallocatorlETStringgRsPgR.tagnum = -1 ;
  G__TClas12ReaderDictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__TClas12ReaderDictLN_TEvioDataEvent.tagnum = -1 ;
  G__TClas12ReaderDictLN_TEvioFileReader.tagnum = -1 ;
  G__TClas12ReaderDictLN_TClas12Reader.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableTClas12ReaderDict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__TClas12ReaderDictLN_vectorlEunsignedsPcharcOallocatorlEunsignedsPchargRsPgR);
   G__get_linked_tagnum_fwd(&G__TClas12ReaderDictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR);
   G__get_linked_tagnum_fwd(&G__TClas12ReaderDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__TClas12ReaderDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__TClas12ReaderDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__TClas12ReaderDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__TClas12ReaderDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR);
   G__get_linked_tagnum_fwd(&G__TClas12ReaderDictLN_TMatrixTBaselEfloatgR);
   G__get_linked_tagnum_fwd(&G__TClas12ReaderDictLN_TMatrixTBaselEdoublegR);
   G__get_linked_tagnum_fwd(&G__TClas12ReaderDictLN_TVectorTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__TClas12ReaderDictLN_TVectorTlEdoublegR);
   G__get_linked_tagnum_fwd(&G__TClas12ReaderDictLN_TElementActionTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__TClas12ReaderDictLN_TElementPosActionTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__TClas12ReaderDictLN_TMatrixTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__TClas12ReaderDictLN_TMatrixTRow_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__TClas12ReaderDictLN_TMatrixTRowlEfloatgR);
   G__get_linked_tagnum_fwd(&G__TClas12ReaderDictLN_TMatrixTDiag_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__TClas12ReaderDictLN_TMatrixTColumn_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__TClas12ReaderDictLN_TMatrixTFlat_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__TClas12ReaderDictLN_TMatrixTSub_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__TClas12ReaderDictLN_TMatrixTSparseRow_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__TClas12ReaderDictLN_TMatrixTSparseDiag_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__TClas12ReaderDictLN_TMatrixTColumnlEfloatgR);
   G__get_linked_tagnum_fwd(&G__TClas12ReaderDictLN_TMatrixTDiaglEfloatgR);
   G__get_linked_tagnum_fwd(&G__TClas12ReaderDictLN_TMatrixTFlatlEfloatgR);
   G__get_linked_tagnum_fwd(&G__TClas12ReaderDictLN_TMatrixTSublEfloatgR);
   G__get_linked_tagnum_fwd(&G__TClas12ReaderDictLN_TMatrixTSparseRowlEfloatgR);
   G__get_linked_tagnum_fwd(&G__TClas12ReaderDictLN_TMatrixTSparseDiaglEfloatgR);
   G__get_linked_tagnum_fwd(&G__TClas12ReaderDictLN_vectorlEintcOallocatorlEintgRsPgR);
   G__get_linked_tagnum_fwd(&G__TClas12ReaderDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__TClas12ReaderDictLN_vectorlEstringcOallocatorlEstringgRsPgR);
   G__get_linked_tagnum_fwd(&G__TClas12ReaderDictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__TClas12ReaderDictLN_TPhysicsEvent);
   G__get_linked_tagnum_fwd(&G__TClas12ReaderDictLN_vectorlEDescriptorEntry_tcOallocatorlEDescriptorEntry_tgRsPgR);
   G__get_linked_tagnum_fwd(&G__TClas12ReaderDictLN_reverse_iteratorlEvectorlEDescriptorEntry_tcOallocatorlEDescriptorEntry_tgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__TClas12ReaderDictLN_maplEintcOvectorlEdoublecOallocatorlEdoublegRsPgRcOlesslEintgRcOallocatorlEpairlEconstsPintcOvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__TClas12ReaderDictLN_maplEintcOvectorlEintcOallocatorlEintgRsPgRcOlesslEintgRcOallocatorlEpairlEconstsPintcOvectorlEintcOallocatorlEintgRsPgRsPgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__TClas12ReaderDictLN_vectorlECompositeADC_tcOallocatorlECompositeADC_tgRsPgR);
   G__get_linked_tagnum_fwd(&G__TClas12ReaderDictLN_reverse_iteratorlEvectorlECompositeADC_tcOallocatorlECompositeADC_tgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__TClas12ReaderDictLN_maplEunsignedsPintcObankIndex_tcOlesslEunsignedsPintgRcOallocatorlEpairlEconstsPunsignedsPintcObankIndex_tgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__TClas12ReaderDictLN_vectorlETStringcOallocatorlETStringgRsPgR);
   G__get_linked_tagnum_fwd(&G__TClas12ReaderDictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__TClas12ReaderDictLN_TEvioDataEvent);
   G__get_linked_tagnum_fwd(&G__TClas12ReaderDictLN_TEvioFileReader);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__TClas12ReaderDictLN_TClas12Reader),sizeof(TClas12Reader),-1,1280,(char*)NULL,G__setup_memvarTClas12Reader,G__setup_memfuncTClas12Reader);
}
extern "C" void G__cpp_setupTClas12ReaderDict(void) {
  G__check_setup_version(30051515,"G__cpp_setupTClas12ReaderDict()");
  G__set_cpp_environmentTClas12ReaderDict();
  G__cpp_setup_tagtableTClas12ReaderDict();

  G__cpp_setup_inheritanceTClas12ReaderDict();

  G__cpp_setup_typetableTClas12ReaderDict();

  G__cpp_setup_memvarTClas12ReaderDict();

  G__cpp_setup_memfuncTClas12ReaderDict();
  G__cpp_setup_globalTClas12ReaderDict();
  G__cpp_setup_funcTClas12ReaderDict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncTClas12ReaderDict();
  return;
}
class G__cpp_setup_initTClas12ReaderDict {
  public:
    G__cpp_setup_initTClas12ReaderDict() { G__add_setup_func("TClas12ReaderDict",(G__incsetup)(&G__cpp_setupTClas12ReaderDict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initTClas12ReaderDict() { G__remove_setup_func("TClas12ReaderDict"); }
};
G__cpp_setup_initTClas12ReaderDict G__cpp_setup_initializerTClas12ReaderDict;

