/********************************************************************
* src/root/TClas12ReaderDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error src/root/TClas12ReaderDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableTClas12ReaderDict();
extern void G__cpp_setup_inheritanceTClas12ReaderDict();
extern void G__cpp_setup_typetableTClas12ReaderDict();
extern void G__cpp_setup_memvarTClas12ReaderDict();
extern void G__cpp_setup_globalTClas12ReaderDict();
extern void G__cpp_setup_memfuncTClas12ReaderDict();
extern void G__cpp_setup_funcTClas12ReaderDict();
extern void G__set_cpp_environmentTClas12ReaderDict();
}


#include "/var/tmp//rootcint_vGQUha.h"
