/********************************************************************
* src/root/TClas12ReaderDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error src/root/TClas12ReaderDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableTClas12ReaderDict();
extern void G__cpp_setup_inheritanceTClas12ReaderDict();
extern void G__cpp_setup_typetableTClas12ReaderDict();
extern void G__cpp_setup_memvarTClas12ReaderDict();
extern void G__cpp_setup_globalTClas12ReaderDict();
extern void G__cpp_setup_memfuncTClas12ReaderDict();
extern void G__cpp_setup_funcTClas12ReaderDict();
extern void G__set_cpp_environmentTClas12ReaderDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "src/root/TClas12Reader.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__TClas12ReaderDictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR;
extern G__linked_taginfo G__TClas12ReaderDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__TClas12ReaderDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TClas12ReaderDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__TClas12ReaderDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TClas12ReaderDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__TClas12ReaderDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__TClas12ReaderDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__TClas12ReaderDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__TClas12ReaderDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__TClas12ReaderDictLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__TClas12ReaderDictLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__TClas12ReaderDictLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__TClas12ReaderDictLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__TClas12ReaderDictLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__TClas12ReaderDictLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__TClas12ReaderDictLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__TClas12ReaderDictLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__TClas12ReaderDictLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__TClas12ReaderDictLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__TClas12ReaderDictLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__TClas12ReaderDictLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__TClas12ReaderDictLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__TClas12ReaderDictLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__TClas12ReaderDictLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__TClas12ReaderDictLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__TClas12ReaderDictLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__TClas12ReaderDictLN_vectorlEintcOallocatorlEintgRsPgR;
extern G__linked_taginfo G__TClas12ReaderDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TClas12ReaderDictLN_vectorlEstringcOallocatorlEstringgRsPgR;
extern G__linked_taginfo G__TClas12ReaderDictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TClas12ReaderDictLN_TPhysicsEvent;
extern G__linked_taginfo G__TClas12ReaderDictLN_vectorlEDescriptorEntry_tcOallocatorlEDescriptorEntry_tgRsPgR;
extern G__linked_taginfo G__TClas12ReaderDictLN_reverse_iteratorlEvectorlEDescriptorEntry_tcOallocatorlEDescriptorEntry_tgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TClas12ReaderDictLN_maplEintcOvectorlEdoublecOallocatorlEdoublegRsPgRcOlesslEintgRcOallocatorlEpairlEconstsPintcOvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRsPgR;
extern G__linked_taginfo G__TClas12ReaderDictLN_maplEintcOvectorlEintcOallocatorlEintgRsPgRcOlesslEintgRcOallocatorlEpairlEconstsPintcOvectorlEintcOallocatorlEintgRsPgRsPgRsPgRsPgR;
extern G__linked_taginfo G__TClas12ReaderDictLN_vectorlECompositeADC_tcOallocatorlECompositeADC_tgRsPgR;
extern G__linked_taginfo G__TClas12ReaderDictLN_reverse_iteratorlEvectorlECompositeADC_tcOallocatorlECompositeADC_tgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TClas12ReaderDictLN_vectorlETStringcOallocatorlETStringgRsPgR;
extern G__linked_taginfo G__TClas12ReaderDictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TClas12ReaderDictLN_TEvioDataEvent;
extern G__linked_taginfo G__TClas12ReaderDictLN_TEvioFileReader;
extern G__linked_taginfo G__TClas12ReaderDictLN_TClas12Reader;

/* STUB derived class for protected member access */
