/**
* Autogenerated Header File for TEvioDataEvent
* \\file TEvioDataEvent.h
* \\author G.Gavalian
* \\date 2014-05-14
*/
#ifndef __TEVIODATAEVENT__
#define __TEVIODATAEVENT__
#include <iostream>
#include <string>
#include <cmath>
#include <vector>
#include "TROOT.h"
#include "TSystem.h"
#include "TObject.h"
#include "TArrayF.h"
#include "TArrayD.h"
#include "TArrayI.h"
#include "TClonesArray.h"
#include "TADCClass.h"
#include "EvioDataEvent.h"

using namespace std;
//! A Brief Description
/*
 * A detailed description
 */
class TEvioDataEvent  : public TObject {

private:
    EvioDataEvent  dataEvent;
public:

/** Default Constructor */
TEvioDataEvent();
/** Default Destructor */
~TEvioDataEvent();
/** Copy Constructor if one is needed */
/*TEvioDataEvent( const TEvioDataEvent &obj); */ 
void init(uint32_t *ptr, int len);

TArrayF   getFloatArray(int tag, int num);
TArrayD   getDoubleArray(int tag, int num);
TArrayI   getIntegerArray(int tag, int num);


TClonesArray  *getFlashADC(int tag, int num);
EvioDataEvent &getDataEvent(){ return dataEvent;};
/** An operator = if one is needed */
/* const TEvioDataEvent &operator=(const TEvioDataEvent &obj); */

ClassDef(TEvioDataEvent,1)

};
#endif
