/********************************************************************
* src/root/TEvioFileReaderDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error src/root/TEvioFileReaderDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableTEvioFileReaderDict();
extern void G__cpp_setup_inheritanceTEvioFileReaderDict();
extern void G__cpp_setup_typetableTEvioFileReaderDict();
extern void G__cpp_setup_memvarTEvioFileReaderDict();
extern void G__cpp_setup_globalTEvioFileReaderDict();
extern void G__cpp_setup_memfuncTEvioFileReaderDict();
extern void G__cpp_setup_funcTEvioFileReaderDict();
extern void G__set_cpp_environmentTEvioFileReaderDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "src/root/TEvioFileReader.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__TEvioFileReaderDictLN_TClass;
extern G__linked_taginfo G__TEvioFileReaderDictLN_TBuffer;
extern G__linked_taginfo G__TEvioFileReaderDictLN_TMemberInspector;
extern G__linked_taginfo G__TEvioFileReaderDictLN_TObject;
extern G__linked_taginfo G__TEvioFileReaderDictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR;
extern G__linked_taginfo G__TEvioFileReaderDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR;
extern G__linked_taginfo G__TEvioFileReaderDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__TEvioFileReaderDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TEvioFileReaderDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__TEvioFileReaderDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TEvioFileReaderDictLN_vectorlEstringcOallocatorlEstringgRsPgR;
extern G__linked_taginfo G__TEvioFileReaderDictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TEvioFileReaderDictLN_vectorlEDescriptorEntry_tcOallocatorlEDescriptorEntry_tgRsPgR;
extern G__linked_taginfo G__TEvioFileReaderDictLN_reverse_iteratorlEvectorlEDescriptorEntry_tcOallocatorlEDescriptorEntry_tgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TEvioFileReaderDictLN_maplEintcOvectorlEdoublecOallocatorlEdoublegRsPgRcOlesslEintgRcOallocatorlEpairlEconstsPintcOvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRsPgR;
extern G__linked_taginfo G__TEvioFileReaderDictLN_vectorlEintcOallocatorlEintgRsPgR;
extern G__linked_taginfo G__TEvioFileReaderDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TEvioFileReaderDictLN_maplEintcOvectorlEintcOallocatorlEintgRsPgRcOlesslEintgRcOallocatorlEpairlEconstsPintcOvectorlEintcOallocatorlEintgRsPgRsPgRsPgRsPgR;
extern G__linked_taginfo G__TEvioFileReaderDictLN_EvioFileReader;
extern G__linked_taginfo G__TEvioFileReaderDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__TEvioFileReaderDictLN_vectorlETStringcOallocatorlETStringgRsPgR;
extern G__linked_taginfo G__TEvioFileReaderDictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TEvioFileReaderDictLN_TArrayD;
extern G__linked_taginfo G__TEvioFileReaderDictLN_TArrayI;
extern G__linked_taginfo G__TEvioFileReaderDictLN_TEvioDataBank;
extern G__linked_taginfo G__TEvioFileReaderDictLN_TEvioDataEvent;
extern G__linked_taginfo G__TEvioFileReaderDictLN_TEvioFileReader;

/* STUB derived class for protected member access */
