//
// File generated by /opt/local/libexec/root5/bin/rootcint at Mon Sep 22 16:22:40 2014

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME srcdIrootdITEvioFileReaderDict
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "TEvioFileReaderDict.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TInterpreter.h"
#include "TVirtualMutex.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// Direct notice to TROOT of the dictionary's loading.
namespace {
   static struct DictInit {
      DictInit() {
         ROOT::RegisterModule();
      }
   } __TheDictionaryInitializer;
}

// START OF SHADOWS

namespace ROOT {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOT
// END OF SHADOWS

namespace ROOT {
   void TEvioFileReader_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void *new_TEvioFileReader(void *p = 0);
   static void *newArray_TEvioFileReader(Long_t size, void *p);
   static void delete_TEvioFileReader(void *p);
   static void deleteArray_TEvioFileReader(void *p);
   static void destruct_TEvioFileReader(void *p);
   static void streamer_TEvioFileReader(TBuffer &buf, void *obj);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::TEvioFileReader*)
   {
      ::TEvioFileReader *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::TEvioFileReader >(0);
      static ::ROOT::TGenericClassInfo 
         instance("TEvioFileReader", ::TEvioFileReader::Class_Version(), "./src/root/TEvioFileReader.h", 50,
                  typeid(::TEvioFileReader), DefineBehavior(ptr, ptr),
                  &::TEvioFileReader::Dictionary, isa_proxy, 0,
                  sizeof(::TEvioFileReader) );
      instance.SetNew(&new_TEvioFileReader);
      instance.SetNewArray(&newArray_TEvioFileReader);
      instance.SetDelete(&delete_TEvioFileReader);
      instance.SetDeleteArray(&deleteArray_TEvioFileReader);
      instance.SetDestructor(&destruct_TEvioFileReader);
      instance.SetStreamerFunc(&streamer_TEvioFileReader);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::TEvioFileReader*)
   {
      return GenerateInitInstanceLocal((::TEvioFileReader*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::TEvioFileReader*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOT

//______________________________________________________________________________
atomic_TClass_ptr TEvioFileReader::fgIsA(0);  // static to hold class pointer

//______________________________________________________________________________
const char *TEvioFileReader::Class_Name()
{
   return "TEvioFileReader";
}

//______________________________________________________________________________
const char *TEvioFileReader::ImplFileName()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::TEvioFileReader*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int TEvioFileReader::ImplFileLine()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::TEvioFileReader*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void TEvioFileReader::Dictionary()
{
   fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::TEvioFileReader*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *TEvioFileReader::Class()
{
   if (!fgIsA) { R__LOCKGUARD2(gCINTMutex); if(!fgIsA) {fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::TEvioFileReader*)0x0)->GetClass();} }
   return fgIsA;
}

//______________________________________________________________________________
void TEvioFileReader::Streamer(TBuffer &R__b)
{
   // Stream an object of class TEvioFileReader.

   UInt_t R__s, R__c;
   if (R__b.IsReading()) {
      Version_t R__v = R__b.ReadVersion(&R__s, &R__c); if (R__v) { }
      TObject::Streamer(R__b);
      R__b.StreamObject(&(reader),typeid(EvioFileReader));
      R__b >> evioFileHandle;
      R__b.ReadStaticArray((unsigned int*)buffer);
      R__b.CheckByteCount(R__s, R__c, TEvioFileReader::IsA());
   } else {
      R__c = R__b.WriteVersion(TEvioFileReader::IsA(), kTRUE);
      TObject::Streamer(R__b);
      R__b.StreamObject(&(reader),typeid(EvioFileReader));
      R__b << evioFileHandle;
      R__b.WriteArray(buffer, 400000);
      R__b.SetByteCount(R__c, kTRUE);
   }
}

//______________________________________________________________________________
void TEvioFileReader::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class TEvioFileReader.
      TClass *R__cl = ::TEvioFileReader::IsA();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "reader", (void*)&reader);
      R__insp.InspectMember("EvioFileReader", (void*)&reader, "reader.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "evioFileHandle", &evioFileHandle);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "buffer[400000]", buffer);
      TObject::ShowMembers(R__insp);
}

namespace ROOT {
   // Wrappers around operator new
   static void *new_TEvioFileReader(void *p) {
      return  p ? new(p) ::TEvioFileReader : new ::TEvioFileReader;
   }
   static void *newArray_TEvioFileReader(Long_t nElements, void *p) {
      return p ? new(p) ::TEvioFileReader[nElements] : new ::TEvioFileReader[nElements];
   }
   // Wrapper around operator delete
   static void delete_TEvioFileReader(void *p) {
      delete ((::TEvioFileReader*)p);
   }
   static void deleteArray_TEvioFileReader(void *p) {
      delete [] ((::TEvioFileReader*)p);
   }
   static void destruct_TEvioFileReader(void *p) {
      typedef ::TEvioFileReader current_t;
      ((current_t*)p)->~current_t();
   }
   // Wrapper around a custom streamer member function.
   static void streamer_TEvioFileReader(TBuffer &buf, void *obj) {
      ((::TEvioFileReader*)obj)->::TEvioFileReader::Streamer(buf);
   }
} // end of namespace ROOT for class ::TEvioFileReader

/********************************************************
* src/root/TEvioFileReaderDict.cc
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtableTEvioFileReaderDict();

extern "C" void G__set_cpp_environmentTEvioFileReaderDict() {
  G__cpp_reset_tagtableTEvioFileReaderDict();
}
#include <new>
extern "C" int G__cpp_dllrevTEvioFileReaderDict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* TEvioFileReader */
static int G__TEvioFileReaderDict_538_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   TEvioFileReader* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new TEvioFileReader[n];
     } else {
       p = new((void*) gvp) TEvioFileReader[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new TEvioFileReader;
     } else {
       p = new((void*) gvp) TEvioFileReader;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__TEvioFileReaderDictLN_TEvioFileReader));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TEvioFileReaderDict_538_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TEvioFileReader*) G__getstructoffset())->open((const char*) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TEvioFileReaderDict_538_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TEvioFileReader*) G__getstructoffset())->close();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TEvioFileReaderDict_538_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((TEvioFileReader*) G__getstructoffset())->next());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TEvioFileReaderDict_538_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((TEvioFileReader*) G__getstructoffset())->getDoubleVector((int) G__int(libp->para[0]), (int) G__int(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TEvioFileReaderDict_538_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((TEvioFileReader*) G__getstructoffset())->getArrayDouble((int) G__int(libp->para[0]), (int) G__int(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TEvioFileReaderDict_538_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((TEvioFileReader*) G__getstructoffset())->getArrayInt((int) G__int(libp->para[0]), (int) G__int(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TEvioFileReaderDict_538_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 2:
      G__letint(result7, 85, (long) ((TEvioFileReader*) G__getstructoffset())->getBank((int) G__int(libp->para[0]), (int) G__int(libp->para[1])));
      break;
   case 1:
      G__letint(result7, 85, (long) ((TEvioFileReader*) G__getstructoffset())->getBank((int) G__int(libp->para[0])));
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TEvioFileReaderDict_538_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 3:
      ((TEvioFileReader*) G__getstructoffset())->getBank(*(TEvioDataBank*) libp->para[0].ref, (int) G__int(libp->para[1])
, (int) G__int(libp->para[2]));
      G__setnull(result7);
      break;
   case 2:
      ((TEvioFileReader*) G__getstructoffset())->getBank(*(TEvioDataBank*) libp->para[0].ref, (int) G__int(libp->para[1]));
      G__setnull(result7);
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TEvioFileReaderDict_538_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TEvioFileReader*) G__getstructoffset())->getEvent(*(TEvioDataEvent*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TEvioFileReaderDict_538_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) TEvioFileReader::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TEvioFileReaderDict_538_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) TEvioFileReader::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TEvioFileReaderDict_538_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) TEvioFileReader::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TEvioFileReaderDict_538_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      TEvioFileReader::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TEvioFileReaderDict_538_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TEvioFileReader*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TEvioFileReaderDict_538_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) TEvioFileReader::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TEvioFileReaderDict_538_0_20(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) TEvioFileReader::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TEvioFileReaderDict_538_0_21(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) TEvioFileReader::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TEvioFileReaderDict_538_0_22(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) TEvioFileReader::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__TEvioFileReaderDict_538_0_23(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   TEvioFileReader* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new TEvioFileReader(*(TEvioFileReader*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__TEvioFileReaderDictLN_TEvioFileReader));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef TEvioFileReader G__TTEvioFileReader;
static int G__TEvioFileReaderDict_538_0_24(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (TEvioFileReader*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((TEvioFileReader*) (soff+(sizeof(TEvioFileReader)*i)))->~G__TTEvioFileReader();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (TEvioFileReader*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((TEvioFileReader*) (soff))->~G__TTEvioFileReader();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__TEvioFileReaderDict_538_0_25(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   TEvioFileReader* dest = (TEvioFileReader*) G__getstructoffset();
   *dest = *(TEvioFileReader*) libp->para[0].ref;
   const TEvioFileReader& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* TEvioFileReader */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncTEvioFileReaderDict {
 public:
  G__Sizep2memfuncTEvioFileReaderDict(): p(&G__Sizep2memfuncTEvioFileReaderDict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncTEvioFileReaderDict::*p)();
};

size_t G__get_sizep2memfuncTEvioFileReaderDict()
{
  G__Sizep2memfuncTEvioFileReaderDict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceTEvioFileReaderDict() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__TEvioFileReaderDictLN_TEvioFileReader))) {
     TEvioFileReader *G__Lderived;
     G__Lderived=(TEvioFileReader*)0x1000;
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__TEvioFileReaderDictLN_TEvioFileReader),G__get_linked_tagnum(&G__TEvioFileReaderDictLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableTEvioFileReaderDict() {

   /* Setting up typedef entry */
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__TEvioFileReaderDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__TEvioFileReaderDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__TEvioFileReaderDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__TEvioFileReaderDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__TEvioFileReaderDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__TEvioFileReaderDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__TEvioFileReaderDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__TEvioFileReaderDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__TEvioFileReaderDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__TEvioFileReaderDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<string>",117,G__get_linked_tagnum(&G__TEvioFileReaderDictLN_vectorlEstringcOallocatorlEstringgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__TEvioFileReaderDictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__TEvioFileReaderDictLN_vectorlEstringcOallocatorlEstringgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__TEvioFileReaderDictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__TEvioFileReaderDictLN_vectorlEstringcOallocatorlEstringgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<DescriptorEntry_t>",117,G__get_linked_tagnum(&G__TEvioFileReaderDictLN_vectorlEDescriptorEntry_tcOallocatorlEDescriptorEntry_tgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__TEvioFileReaderDictLN_reverse_iteratorlEvectorlEDescriptorEntry_tcOallocatorlEDescriptorEntry_tgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__TEvioFileReaderDictLN_vectorlEDescriptorEntry_tcOallocatorlEDescriptorEntry_tgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__TEvioFileReaderDictLN_reverse_iteratorlEvectorlEDescriptorEntry_tcOallocatorlEDescriptorEntry_tgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__TEvioFileReaderDictLN_vectorlEDescriptorEntry_tcOallocatorlEDescriptorEntry_tgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<int,vector<double> >",117,G__get_linked_tagnum(&G__TEvioFileReaderDictLN_maplEintcOvectorlEdoublecOallocatorlEdoublegRsPgRcOlesslEintgRcOallocatorlEpairlEconstsPintcOvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<int,vector<double,allocator<double> > >",117,G__get_linked_tagnum(&G__TEvioFileReaderDictLN_maplEintcOvectorlEdoublecOallocatorlEdoublegRsPgRcOlesslEintgRcOallocatorlEpairlEconstsPintcOvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<int,vector<double,allocator<double> >,less<int> >",117,G__get_linked_tagnum(&G__TEvioFileReaderDictLN_maplEintcOvectorlEdoublecOallocatorlEdoublegRsPgRcOlesslEintgRcOallocatorlEpairlEconstsPintcOvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<int32_t>",117,G__get_linked_tagnum(&G__TEvioFileReaderDictLN_vectorlEintcOallocatorlEintgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__TEvioFileReaderDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__TEvioFileReaderDictLN_vectorlEintcOallocatorlEintgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__TEvioFileReaderDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__TEvioFileReaderDictLN_vectorlEintcOallocatorlEintgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<int>",117,G__get_linked_tagnum(&G__TEvioFileReaderDictLN_vectorlEintcOallocatorlEintgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<int,vector<int32_t> >",117,G__get_linked_tagnum(&G__TEvioFileReaderDictLN_maplEintcOvectorlEintcOallocatorlEintgRsPgRcOlesslEintgRcOallocatorlEpairlEconstsPintcOvectorlEintcOallocatorlEintgRsPgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<int,vector<int,allocator<int> > >",117,G__get_linked_tagnum(&G__TEvioFileReaderDictLN_maplEintcOvectorlEintcOallocatorlEintgRsPgRcOlesslEintgRcOallocatorlEpairlEconstsPintcOvectorlEintcOallocatorlEintgRsPgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<int,vector<int,allocator<int> >,less<int> >",117,G__get_linked_tagnum(&G__TEvioFileReaderDictLN_maplEintcOvectorlEintcOallocatorlEintgRsPgRcOlesslEintgRcOallocatorlEpairlEconstsPintcOvectorlEintcOallocatorlEintgRsPgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<CompositeADC_t>",117,G__get_linked_tagnum(&G__TEvioFileReaderDictLN_vectorlECompositeADC_tcOallocatorlECompositeADC_tgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__TEvioFileReaderDictLN_reverse_iteratorlEvectorlECompositeADC_tcOallocatorlECompositeADC_tgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__TEvioFileReaderDictLN_vectorlECompositeADC_tcOallocatorlECompositeADC_tgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__TEvioFileReaderDictLN_reverse_iteratorlEvectorlECompositeADC_tcOallocatorlECompositeADC_tgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__TEvioFileReaderDictLN_vectorlECompositeADC_tcOallocatorlECompositeADC_tgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<uint32_t>",117,G__get_linked_tagnum(&G__TEvioFileReaderDictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<std::bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__TEvioFileReaderDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__TEvioFileReaderDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*>",117,G__get_linked_tagnum(&G__TEvioFileReaderDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long>",117,G__get_linked_tagnum(&G__TEvioFileReaderDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long,const TObject**>",117,G__get_linked_tagnum(&G__TEvioFileReaderDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<UInt_t>",117,G__get_linked_tagnum(&G__TEvioFileReaderDictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TString>",117,G__get_linked_tagnum(&G__TEvioFileReaderDictLN_vectorlETStringcOallocatorlETStringgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__TEvioFileReaderDictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__TEvioFileReaderDictLN_vectorlETStringcOallocatorlETStringgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__TEvioFileReaderDictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__TEvioFileReaderDictLN_vectorlETStringcOallocatorlETStringgRsPgR));
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* TEvioFileReader */
static void G__setup_memvarTEvioFileReader(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__TEvioFileReaderDictLN_TEvioFileReader));
   { TEvioFileReader *p; p=(TEvioFileReader*)0x1000; if (p) { }
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__TEvioFileReaderDictLN_EvioFileReader),-1,-1,4,"reader=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,-1,-1,4,"evioFileHandle=",0,(char*)NULL);
   G__memvar_setup((void*)0,104,0,0,-1,G__defined_typename("uint32_t"),-1,4,"buffer[400000]=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__TEvioFileReaderDictLN_TClass),G__defined_typename("atomic_TClass_ptr"),-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarTEvioFileReaderDict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncTEvioFileReader(void) {
   /* TEvioFileReader */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__TEvioFileReaderDictLN_TEvioFileReader));
   G__memfunc_setup("TEvioFileReader",1466,G__TEvioFileReaderDict_538_0_1, 105, G__get_linked_tagnum(&G__TEvioFileReaderDictLN_TEvioFileReader), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("open",434,G__TEvioFileReaderDict_538_0_2, 121, -1, -1, 0, 1, 1, 1, 0, "C - - 10 - filename", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("close",534,G__TEvioFileReaderDict_538_0_3, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("next",447,G__TEvioFileReaderDict_538_0_4, 103, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("getDoubleVector",1550,G__TEvioFileReaderDict_538_0_5, 85, G__get_linked_tagnum(&G__TEvioFileReaderDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR), G__defined_typename("vector<double>"), 0, 2, 1, 1, 0, 
"i - - 0 - tag i - - 0 - num", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("getArrayDouble",1434,G__TEvioFileReaderDict_538_0_6, 85, G__get_linked_tagnum(&G__TEvioFileReaderDictLN_TArrayD), -1, 0, 2, 1, 1, 0, 
"i - - 0 - tag i - - 0 - num", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("getArrayInt",1130,G__TEvioFileReaderDict_538_0_7, 85, G__get_linked_tagnum(&G__TEvioFileReaderDictLN_TArrayI), -1, 0, 2, 1, 1, 0, 
"i - - 0 - tag i - - 0 - num", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("getBank",700,G__TEvioFileReaderDict_538_0_8, 85, G__get_linked_tagnum(&G__TEvioFileReaderDictLN_TEvioDataBank), -1, 0, 2, 1, 1, 0, 
"i - - 0 - tag i - - 0 '0' num", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("getBank",700,G__TEvioFileReaderDict_538_0_9, 121, -1, -1, 0, 3, 1, 1, 0, 
"u 'TEvioDataBank' - 1 - bank i - - 0 - tag "
"i - - 0 '0' num", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("getEvent",834,G__TEvioFileReaderDict_538_0_10, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TEvioDataEvent' - 1 - event", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Class",502,G__TEvioFileReaderDict_538_0_11, 85, G__get_linked_tagnum(&G__TEvioFileReaderDictLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&TEvioFileReader::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__TEvioFileReaderDict_538_0_12, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&TEvioFileReader::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__TEvioFileReaderDict_538_0_13, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&TEvioFileReader::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__TEvioFileReaderDict_538_0_14, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&TEvioFileReader::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__TEvioFileReaderDictLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__TEvioFileReaderDict_538_0_18, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - ClassDef_StreamerNVirtual_b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__TEvioFileReaderDict_538_0_19, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&TEvioFileReader::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__TEvioFileReaderDict_538_0_20, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&TEvioFileReader::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__TEvioFileReaderDict_538_0_21, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&TEvioFileReader::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__TEvioFileReaderDict_538_0_22, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&TEvioFileReader::DeclFileLine) ), 0);
   // automatic copy constructor
   G__memfunc_setup("TEvioFileReader", 1466, G__TEvioFileReaderDict_538_0_23, (int) ('i'), G__get_linked_tagnum(&G__TEvioFileReaderDictLN_TEvioFileReader), -1, 0, 1, 1, 1, 0, "u 'TEvioFileReader' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~TEvioFileReader", 1592, G__TEvioFileReaderDict_538_0_24, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__TEvioFileReaderDict_538_0_25, (int) ('u'), G__get_linked_tagnum(&G__TEvioFileReaderDictLN_TEvioFileReader), -1, 1, 1, 1, 1, 0, "u 'TEvioFileReader' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncTEvioFileReaderDict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
}

static void G__cpp_setup_global2() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalTEvioFileReaderDict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {
}

static void G__cpp_setup_func16() {
}

static void G__cpp_setup_func17() {
}

static void G__cpp_setup_func18() {
}

static void G__cpp_setup_func19() {
}

static void G__cpp_setup_func20() {
}

static void G__cpp_setup_func21() {
}

static void G__cpp_setup_func22() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcTEvioFileReaderDict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
  G__cpp_setup_func16();
  G__cpp_setup_func17();
  G__cpp_setup_func18();
  G__cpp_setup_func19();
  G__cpp_setup_func20();
  G__cpp_setup_func21();
  G__cpp_setup_func22();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__TEvioFileReaderDictLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__TEvioFileReaderDictLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__TEvioFileReaderDictLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__TEvioFileReaderDictLN_TObject = { "TObject" , 99 , -1 };
G__linked_taginfo G__TEvioFileReaderDictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR = { "vector<unsigned int,allocator<unsigned int> >" , 99 , -1 };
G__linked_taginfo G__TEvioFileReaderDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR = { "vector<double,allocator<double> >" , 99 , -1 };
G__linked_taginfo G__TEvioFileReaderDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__TEvioFileReaderDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__TEvioFileReaderDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__TEvioFileReaderDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__TEvioFileReaderDictLN_vectorlEstringcOallocatorlEstringgRsPgR = { "vector<string,allocator<string> >" , 99 , -1 };
G__linked_taginfo G__TEvioFileReaderDictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<string,allocator<string> >::iterator>" , 99 , -1 };
G__linked_taginfo G__TEvioFileReaderDictLN_vectorlEDescriptorEntry_tcOallocatorlEDescriptorEntry_tgRsPgR = { "vector<DescriptorEntry_t,allocator<DescriptorEntry_t> >" , 99 , -1 };
G__linked_taginfo G__TEvioFileReaderDictLN_reverse_iteratorlEvectorlEDescriptorEntry_tcOallocatorlEDescriptorEntry_tgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<DescriptorEntry_t,allocator<DescriptorEntry_t> >::iterator>" , 99 , -1 };
G__linked_taginfo G__TEvioFileReaderDictLN_maplEintcOvectorlEdoublecOallocatorlEdoublegRsPgRcOlesslEintgRcOallocatorlEpairlEconstsPintcOvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRsPgR = { "map<int,vector<double,allocator<double> >,less<int>,allocator<pair<const int,vector<double,allocator<double> > > > >" , 99 , -1 };
G__linked_taginfo G__TEvioFileReaderDictLN_vectorlEintcOallocatorlEintgRsPgR = { "vector<int,allocator<int> >" , 99 , -1 };
G__linked_taginfo G__TEvioFileReaderDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<int,allocator<int> >::iterator>" , 99 , -1 };
G__linked_taginfo G__TEvioFileReaderDictLN_maplEintcOvectorlEintcOallocatorlEintgRsPgRcOlesslEintgRcOallocatorlEpairlEconstsPintcOvectorlEintcOallocatorlEintgRsPgRsPgRsPgRsPgR = { "map<int,vector<int,allocator<int> >,less<int>,allocator<pair<const int,vector<int,allocator<int> > > > >" , 99 , -1 };
G__linked_taginfo G__TEvioFileReaderDictLN_vectorlECompositeADC_tcOallocatorlECompositeADC_tgRsPgR = { "vector<CompositeADC_t,allocator<CompositeADC_t> >" , 99 , -1 };
G__linked_taginfo G__TEvioFileReaderDictLN_reverse_iteratorlEvectorlECompositeADC_tcOallocatorlECompositeADC_tgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<CompositeADC_t,allocator<CompositeADC_t> >::iterator>" , 99 , -1 };
G__linked_taginfo G__TEvioFileReaderDictLN_EvioFileReader = { "EvioFileReader" , 99 , -1 };
G__linked_taginfo G__TEvioFileReaderDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR = { "iterator<bidirectional_iterator_tag,TObject*,long,const TObject**,const TObject*&>" , 115 , -1 };
G__linked_taginfo G__TEvioFileReaderDictLN_vectorlETStringcOallocatorlETStringgRsPgR = { "vector<TString,allocator<TString> >" , 99 , -1 };
G__linked_taginfo G__TEvioFileReaderDictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TString,allocator<TString> >::iterator>" , 99 , -1 };
G__linked_taginfo G__TEvioFileReaderDictLN_TArrayD = { "TArrayD" , 99 , -1 };
G__linked_taginfo G__TEvioFileReaderDictLN_TArrayI = { "TArrayI" , 99 , -1 };
G__linked_taginfo G__TEvioFileReaderDictLN_TEvioDataBank = { "TEvioDataBank" , 99 , -1 };
G__linked_taginfo G__TEvioFileReaderDictLN_TEvioDataEvent = { "TEvioDataEvent" , 99 , -1 };
G__linked_taginfo G__TEvioFileReaderDictLN_TEvioFileReader = { "TEvioFileReader" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableTEvioFileReaderDict() {
  G__TEvioFileReaderDictLN_TClass.tagnum = -1 ;
  G__TEvioFileReaderDictLN_TBuffer.tagnum = -1 ;
  G__TEvioFileReaderDictLN_TMemberInspector.tagnum = -1 ;
  G__TEvioFileReaderDictLN_TObject.tagnum = -1 ;
  G__TEvioFileReaderDictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR.tagnum = -1 ;
  G__TEvioFileReaderDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR.tagnum = -1 ;
  G__TEvioFileReaderDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__TEvioFileReaderDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__TEvioFileReaderDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__TEvioFileReaderDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__TEvioFileReaderDictLN_vectorlEstringcOallocatorlEstringgRsPgR.tagnum = -1 ;
  G__TEvioFileReaderDictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__TEvioFileReaderDictLN_vectorlEDescriptorEntry_tcOallocatorlEDescriptorEntry_tgRsPgR.tagnum = -1 ;
  G__TEvioFileReaderDictLN_reverse_iteratorlEvectorlEDescriptorEntry_tcOallocatorlEDescriptorEntry_tgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__TEvioFileReaderDictLN_maplEintcOvectorlEdoublecOallocatorlEdoublegRsPgRcOlesslEintgRcOallocatorlEpairlEconstsPintcOvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRsPgR.tagnum = -1 ;
  G__TEvioFileReaderDictLN_vectorlEintcOallocatorlEintgRsPgR.tagnum = -1 ;
  G__TEvioFileReaderDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__TEvioFileReaderDictLN_maplEintcOvectorlEintcOallocatorlEintgRsPgRcOlesslEintgRcOallocatorlEpairlEconstsPintcOvectorlEintcOallocatorlEintgRsPgRsPgRsPgRsPgR.tagnum = -1 ;
  G__TEvioFileReaderDictLN_vectorlECompositeADC_tcOallocatorlECompositeADC_tgRsPgR.tagnum = -1 ;
  G__TEvioFileReaderDictLN_reverse_iteratorlEvectorlECompositeADC_tcOallocatorlECompositeADC_tgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__TEvioFileReaderDictLN_EvioFileReader.tagnum = -1 ;
  G__TEvioFileReaderDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR.tagnum = -1 ;
  G__TEvioFileReaderDictLN_vectorlETStringcOallocatorlETStringgRsPgR.tagnum = -1 ;
  G__TEvioFileReaderDictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__TEvioFileReaderDictLN_TArrayD.tagnum = -1 ;
  G__TEvioFileReaderDictLN_TArrayI.tagnum = -1 ;
  G__TEvioFileReaderDictLN_TEvioDataBank.tagnum = -1 ;
  G__TEvioFileReaderDictLN_TEvioDataEvent.tagnum = -1 ;
  G__TEvioFileReaderDictLN_TEvioFileReader.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableTEvioFileReaderDict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__TEvioFileReaderDictLN_TClass);
   G__get_linked_tagnum_fwd(&G__TEvioFileReaderDictLN_TBuffer);
   G__get_linked_tagnum_fwd(&G__TEvioFileReaderDictLN_TMemberInspector);
   G__get_linked_tagnum_fwd(&G__TEvioFileReaderDictLN_TObject);
   G__get_linked_tagnum_fwd(&G__TEvioFileReaderDictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR);
   G__get_linked_tagnum_fwd(&G__TEvioFileReaderDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR);
   G__get_linked_tagnum_fwd(&G__TEvioFileReaderDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__TEvioFileReaderDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__TEvioFileReaderDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__TEvioFileReaderDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__TEvioFileReaderDictLN_vectorlEstringcOallocatorlEstringgRsPgR);
   G__get_linked_tagnum_fwd(&G__TEvioFileReaderDictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__TEvioFileReaderDictLN_vectorlEDescriptorEntry_tcOallocatorlEDescriptorEntry_tgRsPgR);
   G__get_linked_tagnum_fwd(&G__TEvioFileReaderDictLN_reverse_iteratorlEvectorlEDescriptorEntry_tcOallocatorlEDescriptorEntry_tgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__TEvioFileReaderDictLN_maplEintcOvectorlEdoublecOallocatorlEdoublegRsPgRcOlesslEintgRcOallocatorlEpairlEconstsPintcOvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__TEvioFileReaderDictLN_vectorlEintcOallocatorlEintgRsPgR);
   G__get_linked_tagnum_fwd(&G__TEvioFileReaderDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__TEvioFileReaderDictLN_maplEintcOvectorlEintcOallocatorlEintgRsPgRcOlesslEintgRcOallocatorlEpairlEconstsPintcOvectorlEintcOallocatorlEintgRsPgRsPgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__TEvioFileReaderDictLN_vectorlECompositeADC_tcOallocatorlECompositeADC_tgRsPgR);
   G__get_linked_tagnum_fwd(&G__TEvioFileReaderDictLN_reverse_iteratorlEvectorlECompositeADC_tcOallocatorlECompositeADC_tgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__TEvioFileReaderDictLN_EvioFileReader);
   G__get_linked_tagnum_fwd(&G__TEvioFileReaderDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR);
   G__get_linked_tagnum_fwd(&G__TEvioFileReaderDictLN_vectorlETStringcOallocatorlETStringgRsPgR);
   G__get_linked_tagnum_fwd(&G__TEvioFileReaderDictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__TEvioFileReaderDictLN_TArrayD);
   G__get_linked_tagnum_fwd(&G__TEvioFileReaderDictLN_TArrayI);
   G__get_linked_tagnum_fwd(&G__TEvioFileReaderDictLN_TEvioDataBank);
   G__get_linked_tagnum_fwd(&G__TEvioFileReaderDictLN_TEvioDataEvent);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__TEvioFileReaderDictLN_TEvioFileReader),sizeof(TEvioFileReader),-1,29952,(char*)NULL,G__setup_memvarTEvioFileReader,G__setup_memfuncTEvioFileReader);
}
extern "C" void G__cpp_setupTEvioFileReaderDict(void) {
  G__check_setup_version(30051515,"G__cpp_setupTEvioFileReaderDict()");
  G__set_cpp_environmentTEvioFileReaderDict();
  G__cpp_setup_tagtableTEvioFileReaderDict();

  G__cpp_setup_inheritanceTEvioFileReaderDict();

  G__cpp_setup_typetableTEvioFileReaderDict();

  G__cpp_setup_memvarTEvioFileReaderDict();

  G__cpp_setup_memfuncTEvioFileReaderDict();
  G__cpp_setup_globalTEvioFileReaderDict();
  G__cpp_setup_funcTEvioFileReaderDict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncTEvioFileReaderDict();
  return;
}
class G__cpp_setup_initTEvioFileReaderDict {
  public:
    G__cpp_setup_initTEvioFileReaderDict() { G__add_setup_func("TEvioFileReaderDict",(G__incsetup)(&G__cpp_setupTEvioFileReaderDict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initTEvioFileReaderDict() { G__remove_setup_func("TEvioFileReaderDict"); }
};
G__cpp_setup_initTEvioFileReaderDict G__cpp_setup_initializerTEvioFileReaderDict;

