/**
* Autogenerated Header File for TEvioDataDescriptor
* \\file TEvioDataDescriptor.h
* \\author G.Gavalian
* \\date 2014-05-14
*/
#ifndef __TEVIODATADESCRIPTOR__
#define __TEVIODATADESCRIPTOR__
#include <iostream>
#include <string>
#include <cmath>
#include <vector>
#include "TROOT.h"
#include "TSystem.h"
#include "TObject.h"
#include "TArrayD.h"
#include "TArrayI.h"
#include "EvioDataDescriptor.h"

using namespace std;
//! A Brief Description
/*
 * A detailed description
 */
class TEvioDataDescriptor  : public TObject {

private:
    EvioDataDescriptor descriptor;
public:

/** Default Constructor */
TEvioDataDescriptor();
TEvioDataDescriptor(int tag, const char *format);
/** Default Destructor */
~TEvioDataDescriptor();
/** Copy Constructor if one is needed */
/*TEvioDataDescriptor( const TEvioDataDescriptor &obj); */ 
/*
void addEntry(const char *name, int num, int type);
void parseFormat(int tag, const char *format);
int  entries();

int  getEntryName(int index);
int  getEntryNum(int index);
int  getEntryType(int index);

int  getTag(){ descriptor.getTag();};
*/
/** An operator = if one is needed */
/* const TEvioDataDescriptor &operator=(const TEvioDataDescriptor &obj); */

ClassDef(TEvioDataDescriptor,1)
        
};
#endif
