//
// File generated by /opt/local/libexec/root5/bin/rootcint at Tue Oct  7 09:50:32 2014

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME srcdIrootdITFileEvioDict
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "TFileEvioDict.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TInterpreter.h"
#include "TVirtualMutex.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// Direct notice to TROOT of the dictionary's loading.
namespace {
   static struct DictInit {
      DictInit() {
         ROOT::RegisterModule();
      }
   } __TheDictionaryInitializer;
}

// START OF SHADOWS

namespace ROOT {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOT
// END OF SHADOWS

namespace ROOT {
   void TFileEvio_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void *new_TFileEvio(void *p = 0);
   static void *newArray_TFileEvio(Long_t size, void *p);
   static void delete_TFileEvio(void *p);
   static void deleteArray_TFileEvio(void *p);
   static void destruct_TFileEvio(void *p);
   static void streamer_TFileEvio(TBuffer &buf, void *obj);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::TFileEvio*)
   {
      ::TFileEvio *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::TFileEvio >(0);
      static ::ROOT::TGenericClassInfo 
         instance("TFileEvio", ::TFileEvio::Class_Version(), "./src/root/TFileEvio.h", 25,
                  typeid(::TFileEvio), DefineBehavior(ptr, ptr),
                  &::TFileEvio::Dictionary, isa_proxy, 0,
                  sizeof(::TFileEvio) );
      instance.SetNew(&new_TFileEvio);
      instance.SetNewArray(&newArray_TFileEvio);
      instance.SetDelete(&delete_TFileEvio);
      instance.SetDeleteArray(&deleteArray_TFileEvio);
      instance.SetDestructor(&destruct_TFileEvio);
      instance.SetStreamerFunc(&streamer_TFileEvio);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::TFileEvio*)
   {
      return GenerateInitInstanceLocal((::TFileEvio*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::TFileEvio*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOT

//______________________________________________________________________________
atomic_TClass_ptr TFileEvio::fgIsA(0);  // static to hold class pointer

//______________________________________________________________________________
const char *TFileEvio::Class_Name()
{
   return "TFileEvio";
}

//______________________________________________________________________________
const char *TFileEvio::ImplFileName()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::TFileEvio*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int TFileEvio::ImplFileLine()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::TFileEvio*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void TFileEvio::Dictionary()
{
   fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::TFileEvio*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *TFileEvio::Class()
{
   if (!fgIsA) { R__LOCKGUARD2(gCINTMutex); if(!fgIsA) {fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::TFileEvio*)0x0)->GetClass();} }
   return fgIsA;
}

//______________________________________________________________________________
void TFileEvio::Streamer(TBuffer &R__b)
{
   // Stream an object of class TFileEvio.

   UInt_t R__s, R__c;
   if (R__b.IsReading()) {
      Version_t R__v = R__b.ReadVersion(&R__s, &R__c); if (R__v) { }
      TDirectory::Streamer(R__b);
      R__b.CheckByteCount(R__s, R__c, TFileEvio::IsA());
   } else {
      R__c = R__b.WriteVersion(TFileEvio::IsA(), kTRUE);
      TDirectory::Streamer(R__b);
      R__b.SetByteCount(R__c, kTRUE);
   }
}

//______________________________________________________________________________
void TFileEvio::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class TFileEvio.
      TClass *R__cl = ::TFileEvio::IsA();
      if (R__cl || R__insp.IsA()) { }
      TDirectory::ShowMembers(R__insp);
}

namespace ROOT {
   // Wrappers around operator new
   static void *new_TFileEvio(void *p) {
      return  p ? new(p) ::TFileEvio : new ::TFileEvio;
   }
   static void *newArray_TFileEvio(Long_t nElements, void *p) {
      return p ? new(p) ::TFileEvio[nElements] : new ::TFileEvio[nElements];
   }
   // Wrapper around operator delete
   static void delete_TFileEvio(void *p) {
      delete ((::TFileEvio*)p);
   }
   static void deleteArray_TFileEvio(void *p) {
      delete [] ((::TFileEvio*)p);
   }
   static void destruct_TFileEvio(void *p) {
      typedef ::TFileEvio current_t;
      ((current_t*)p)->~current_t();
   }
   // Wrapper around a custom streamer member function.
   static void streamer_TFileEvio(TBuffer &buf, void *obj) {
      ((::TFileEvio*)obj)->::TFileEvio::Streamer(buf);
   }
} // end of namespace ROOT for class ::TFileEvio

/********************************************************
* src/root/TFileEvioDict.cc
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtableTFileEvioDict();

extern "C" void G__set_cpp_environmentTFileEvioDict() {
  G__cpp_reset_tagtableTFileEvioDict();
}
#include <new>
extern "C" int G__cpp_dllrevTFileEvioDict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* TFileEvio */
static int G__TFileEvioDict_582_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   TFileEvio* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new TFileEvio[n];
     } else {
       p = new((void*) gvp) TFileEvio[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new TFileEvio;
     } else {
       p = new((void*) gvp) TFileEvio;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__TFileEvioDictLN_TFileEvio));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TFileEvioDict_582_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   TFileEvio* p = NULL;
   char* gvp = (char*) G__getgvp();
   //m: 1
   if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
     p = new TFileEvio((const char*) G__int(libp->para[0]));
   } else {
     p = new((void*) gvp) TFileEvio((const char*) G__int(libp->para[0]));
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__TFileEvioDictLN_TFileEvio));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TFileEvioDict_582_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((TFileEvio*) G__getstructoffset())->Browse());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TFileEvioDict_582_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TFileEvio*) G__getstructoffset())->ReadFile((const char*) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TFileEvioDict_582_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) TFileEvio::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TFileEvioDict_582_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) TFileEvio::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TFileEvioDict_582_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) TFileEvio::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TFileEvioDict_582_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      TFileEvio::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TFileEvioDict_582_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TFileEvio*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TFileEvioDict_582_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) TFileEvio::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TFileEvioDict_582_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) TFileEvio::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TFileEvioDict_582_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) TFileEvio::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TFileEvioDict_582_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) TFileEvio::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__TFileEvioDict_582_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   TFileEvio* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new TFileEvio(*(TFileEvio*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__TFileEvioDictLN_TFileEvio));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef TFileEvio G__TTFileEvio;
static int G__TFileEvioDict_582_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (TFileEvio*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((TFileEvio*) (soff+(sizeof(TFileEvio)*i)))->~G__TTFileEvio();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (TFileEvio*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((TFileEvio*) (soff))->~G__TTFileEvio();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* TFileEvio */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncTFileEvioDict {
 public:
  G__Sizep2memfuncTFileEvioDict(): p(&G__Sizep2memfuncTFileEvioDict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncTFileEvioDict::*p)();
};

size_t G__get_sizep2memfuncTFileEvioDict()
{
  G__Sizep2memfuncTFileEvioDict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceTFileEvioDict() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__TFileEvioDictLN_TFileEvio))) {
     TFileEvio *G__Lderived;
     G__Lderived=(TFileEvio*)0x1000;
     {
       TDirectory *G__Lpbase=(TDirectory*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__TFileEvioDictLN_TFileEvio),G__get_linked_tagnum(&G__TFileEvioDictLN_TDirectory),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
     {
       TNamed *G__Lpbase=(TNamed*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__TFileEvioDictLN_TFileEvio),G__get_linked_tagnum(&G__TFileEvioDictLN_TNamed),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__TFileEvioDictLN_TFileEvio),G__get_linked_tagnum(&G__TFileEvioDictLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableTFileEvioDict() {

   /* Setting up typedef entry */
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__TFileEvioDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__TFileEvioDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__TFileEvioDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__TFileEvioDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__TFileEvioDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__TFileEvioDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__TFileEvioDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__TFileEvioDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__TFileEvioDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__TFileEvioDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Float_t>",117,G__get_linked_tagnum(&G__TFileEvioDictLN_TVectorTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Double_t>",117,G__get_linked_tagnum(&G__TFileEvioDictLN_TVectorTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<std::bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__TFileEvioDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__TFileEvioDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*>",117,G__get_linked_tagnum(&G__TFileEvioDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long>",117,G__get_linked_tagnum(&G__TFileEvioDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long,const TObject**>",117,G__get_linked_tagnum(&G__TFileEvioDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<string>",117,G__get_linked_tagnum(&G__TFileEvioDictLN_vectorlEstringcOallocatorlEstringgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__TFileEvioDictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__TFileEvioDictLN_vectorlEstringcOallocatorlEstringgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__TFileEvioDictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__TFileEvioDictLN_vectorlEstringcOallocatorlEstringgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<DescriptorEntry_t>",117,G__get_linked_tagnum(&G__TFileEvioDictLN_vectorlEDescriptorEntry_tcOallocatorlEDescriptorEntry_tgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__TFileEvioDictLN_reverse_iteratorlEvectorlEDescriptorEntry_tcOallocatorlEDescriptorEntry_tgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__TFileEvioDictLN_vectorlEDescriptorEntry_tcOallocatorlEDescriptorEntry_tgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__TFileEvioDictLN_reverse_iteratorlEvectorlEDescriptorEntry_tcOallocatorlEDescriptorEntry_tgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__TFileEvioDictLN_vectorlEDescriptorEntry_tcOallocatorlEDescriptorEntry_tgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<int,vector<double> >",117,G__get_linked_tagnum(&G__TFileEvioDictLN_maplEintcOvectorlEdoublecOallocatorlEdoublegRsPgRcOlesslEintgRcOallocatorlEpairlEconstsPintcOvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<int,vector<double,allocator<double> > >",117,G__get_linked_tagnum(&G__TFileEvioDictLN_maplEintcOvectorlEdoublecOallocatorlEdoublegRsPgRcOlesslEintgRcOallocatorlEpairlEconstsPintcOvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<int,vector<double,allocator<double> >,less<int> >",117,G__get_linked_tagnum(&G__TFileEvioDictLN_maplEintcOvectorlEdoublecOallocatorlEdoublegRsPgRcOlesslEintgRcOallocatorlEpairlEconstsPintcOvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<int32_t>",117,G__get_linked_tagnum(&G__TFileEvioDictLN_vectorlEintcOallocatorlEintgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__TFileEvioDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__TFileEvioDictLN_vectorlEintcOallocatorlEintgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__TFileEvioDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__TFileEvioDictLN_vectorlEintcOallocatorlEintgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<int>",117,G__get_linked_tagnum(&G__TFileEvioDictLN_vectorlEintcOallocatorlEintgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<int,vector<int32_t> >",117,G__get_linked_tagnum(&G__TFileEvioDictLN_maplEintcOvectorlEintcOallocatorlEintgRsPgRcOlesslEintgRcOallocatorlEpairlEconstsPintcOvectorlEintcOallocatorlEintgRsPgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<int,vector<int,allocator<int> > >",117,G__get_linked_tagnum(&G__TFileEvioDictLN_maplEintcOvectorlEintcOallocatorlEintgRsPgRcOlesslEintgRcOallocatorlEpairlEconstsPintcOvectorlEintcOallocatorlEintgRsPgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<int,vector<int,allocator<int> >,less<int> >",117,G__get_linked_tagnum(&G__TFileEvioDictLN_maplEintcOvectorlEintcOallocatorlEintgRsPgRcOlesslEintgRcOallocatorlEpairlEconstsPintcOvectorlEintcOallocatorlEintgRsPgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<CompositeADC_t>",117,G__get_linked_tagnum(&G__TFileEvioDictLN_vectorlECompositeADC_tcOallocatorlECompositeADC_tgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__TFileEvioDictLN_reverse_iteratorlEvectorlECompositeADC_tcOallocatorlECompositeADC_tgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__TFileEvioDictLN_vectorlECompositeADC_tcOallocatorlECompositeADC_tgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__TFileEvioDictLN_reverse_iteratorlEvectorlECompositeADC_tcOallocatorlECompositeADC_tgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__TFileEvioDictLN_vectorlECompositeADC_tcOallocatorlECompositeADC_tgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<uint32_t>",117,G__get_linked_tagnum(&G__TFileEvioDictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<uint32_t,bankIndex_t>",117,G__get_linked_tagnum(&G__TFileEvioDictLN_maplEunsignedsPintcObankIndex_tcOlesslEunsignedsPintgRcOallocatorlEpairlEconstsPunsignedsPintcObankIndex_tgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<unsigned int,bankIndex_t>",117,G__get_linked_tagnum(&G__TFileEvioDictLN_maplEunsignedsPintcObankIndex_tcOlesslEunsignedsPintgRcOallocatorlEpairlEconstsPunsignedsPintcObankIndex_tgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<unsigned int,bankIndex_t,less<unsigned int> >",117,G__get_linked_tagnum(&G__TFileEvioDictLN_maplEunsignedsPintcObankIndex_tcOlesslEunsignedsPintgRcOallocatorlEpairlEconstsPunsignedsPintcObankIndex_tgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<uint8_t>",117,G__get_linked_tagnum(&G__TFileEvioDictLN_vectorlEunsignedsPcharcOallocatorlEunsignedsPchargRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<UInt_t>",117,G__get_linked_tagnum(&G__TFileEvioDictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TString>",117,G__get_linked_tagnum(&G__TFileEvioDictLN_vectorlETStringcOallocatorlETStringgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__TFileEvioDictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__TFileEvioDictLN_vectorlETStringcOallocatorlETStringgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__TFileEvioDictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__TFileEvioDictLN_vectorlETStringcOallocatorlETStringgRsPgR));
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* TFileEvio */
static void G__setup_memvarTFileEvio(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__TFileEvioDictLN_TFileEvio));
   { TFileEvio *p; p=(TFileEvio*)0x1000; if (p) { }
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__TFileEvioDictLN_TClass),G__defined_typename("atomic_TClass_ptr"),-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarTFileEvioDict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncTFileEvio(void) {
   /* TFileEvio */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__TFileEvioDictLN_TFileEvio));
   G__memfunc_setup("GetNameFromArray",1588,(G__InterfaceMethod) NULL, 67, -1, -1, 0, 1, 1, 4, 0, "u 'TArrayC' - 1 - array", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("TFileEvio",871,G__TFileEvioDict_582_0_2, 105, G__get_linked_tagnum(&G__TFileEvioDictLN_TFileEvio), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("TFileEvio",871,G__TFileEvioDict_582_0_3, 105, G__get_linked_tagnum(&G__TFileEvioDictLN_TFileEvio), -1, 0, 1, 1, 1, 0, "C - - 10 - filename", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Browse",626,G__TFileEvioDict_582_0_4, 85, G__get_linked_tagnum(&G__TFileEvioDictLN_TBrowser), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("ReadFile",764,G__TFileEvioDict_582_0_5, 121, -1, -1, 0, 1, 1, 1, 0, "C - - 10 - filename", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Class",502,G__TFileEvioDict_582_0_6, 85, G__get_linked_tagnum(&G__TFileEvioDictLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&TFileEvio::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__TFileEvioDict_582_0_7, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&TFileEvio::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__TFileEvioDict_582_0_8, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&TFileEvio::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__TFileEvioDict_582_0_9, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&TFileEvio::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__TFileEvioDictLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__TFileEvioDict_582_0_13, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - ClassDef_StreamerNVirtual_b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__TFileEvioDict_582_0_14, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&TFileEvio::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__TFileEvioDict_582_0_15, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&TFileEvio::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__TFileEvioDict_582_0_16, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&TFileEvio::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__TFileEvioDict_582_0_17, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&TFileEvio::DeclFileLine) ), 0);
   // automatic copy constructor
   G__memfunc_setup("TFileEvio", 871, G__TFileEvioDict_582_0_18, (int) ('i'), G__get_linked_tagnum(&G__TFileEvioDictLN_TFileEvio), -1, 0, 1, 1, 1, 0, "u 'TFileEvio' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~TFileEvio", 997, G__TFileEvioDict_582_0_19, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncTFileEvioDict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
}

static void G__cpp_setup_global2() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalTFileEvioDict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {
}

static void G__cpp_setup_func16() {
}

static void G__cpp_setup_func17() {
}

static void G__cpp_setup_func18() {
}

static void G__cpp_setup_func19() {
}

static void G__cpp_setup_func20() {
}

static void G__cpp_setup_func21() {
}

static void G__cpp_setup_func22() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcTFileEvioDict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
  G__cpp_setup_func16();
  G__cpp_setup_func17();
  G__cpp_setup_func18();
  G__cpp_setup_func19();
  G__cpp_setup_func20();
  G__cpp_setup_func21();
  G__cpp_setup_func22();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__TFileEvioDictLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__TFileEvioDictLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__TFileEvioDictLN_TDirectory = { "TDirectory" , 99 , -1 };
G__linked_taginfo G__TFileEvioDictLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__TFileEvioDictLN_TObject = { "TObject" , 99 , -1 };
G__linked_taginfo G__TFileEvioDictLN_TNamed = { "TNamed" , 99 , -1 };
G__linked_taginfo G__TFileEvioDictLN_vectorlEunsignedsPcharcOallocatorlEunsignedsPchargRsPgR = { "vector<unsigned char,allocator<unsigned char> >" , 99 , -1 };
G__linked_taginfo G__TFileEvioDictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR = { "vector<unsigned int,allocator<unsigned int> >" , 99 , -1 };
G__linked_taginfo G__TFileEvioDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__TFileEvioDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__TFileEvioDictLN_TBrowser = { "TBrowser" , 99 , -1 };
G__linked_taginfo G__TFileEvioDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__TFileEvioDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__TFileEvioDictLN_TArrayC = { "TArrayC" , 99 , -1 };
G__linked_taginfo G__TFileEvioDictLN_TVectorTlEfloatgR = { "TVectorT<float>" , 99 , -1 };
G__linked_taginfo G__TFileEvioDictLN_TVectorTlEdoublegR = { "TVectorT<double>" , 99 , -1 };
G__linked_taginfo G__TFileEvioDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR = { "iterator<bidirectional_iterator_tag,TObject*,long,const TObject**,const TObject*&>" , 115 , -1 };
G__linked_taginfo G__TFileEvioDictLN_vectorlEstringcOallocatorlEstringgRsPgR = { "vector<string,allocator<string> >" , 99 , -1 };
G__linked_taginfo G__TFileEvioDictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<string,allocator<string> >::iterator>" , 99 , -1 };
G__linked_taginfo G__TFileEvioDictLN_vectorlEDescriptorEntry_tcOallocatorlEDescriptorEntry_tgRsPgR = { "vector<DescriptorEntry_t,allocator<DescriptorEntry_t> >" , 99 , -1 };
G__linked_taginfo G__TFileEvioDictLN_reverse_iteratorlEvectorlEDescriptorEntry_tcOallocatorlEDescriptorEntry_tgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<DescriptorEntry_t,allocator<DescriptorEntry_t> >::iterator>" , 99 , -1 };
G__linked_taginfo G__TFileEvioDictLN_maplEintcOvectorlEdoublecOallocatorlEdoublegRsPgRcOlesslEintgRcOallocatorlEpairlEconstsPintcOvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRsPgR = { "map<int,vector<double,allocator<double> >,less<int>,allocator<pair<const int,vector<double,allocator<double> > > > >" , 99 , -1 };
G__linked_taginfo G__TFileEvioDictLN_vectorlEintcOallocatorlEintgRsPgR = { "vector<int,allocator<int> >" , 99 , -1 };
G__linked_taginfo G__TFileEvioDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<int,allocator<int> >::iterator>" , 99 , -1 };
G__linked_taginfo G__TFileEvioDictLN_maplEintcOvectorlEintcOallocatorlEintgRsPgRcOlesslEintgRcOallocatorlEpairlEconstsPintcOvectorlEintcOallocatorlEintgRsPgRsPgRsPgRsPgR = { "map<int,vector<int,allocator<int> >,less<int>,allocator<pair<const int,vector<int,allocator<int> > > > >" , 99 , -1 };
G__linked_taginfo G__TFileEvioDictLN_vectorlECompositeADC_tcOallocatorlECompositeADC_tgRsPgR = { "vector<CompositeADC_t,allocator<CompositeADC_t> >" , 99 , -1 };
G__linked_taginfo G__TFileEvioDictLN_reverse_iteratorlEvectorlECompositeADC_tcOallocatorlECompositeADC_tgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<CompositeADC_t,allocator<CompositeADC_t> >::iterator>" , 99 , -1 };
G__linked_taginfo G__TFileEvioDictLN_maplEunsignedsPintcObankIndex_tcOlesslEunsignedsPintgRcOallocatorlEpairlEconstsPunsignedsPintcObankIndex_tgRsPgRsPgR = { "map<unsigned int,bankIndex_t,less<unsigned int>,allocator<pair<const unsigned int,bankIndex_t> > >" , 99 , -1 };
G__linked_taginfo G__TFileEvioDictLN_vectorlETStringcOallocatorlETStringgRsPgR = { "vector<TString,allocator<TString> >" , 99 , -1 };
G__linked_taginfo G__TFileEvioDictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TString,allocator<TString> >::iterator>" , 99 , -1 };
G__linked_taginfo G__TFileEvioDictLN_TFileEvio = { "TFileEvio" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableTFileEvioDict() {
  G__TFileEvioDictLN_TClass.tagnum = -1 ;
  G__TFileEvioDictLN_TBuffer.tagnum = -1 ;
  G__TFileEvioDictLN_TDirectory.tagnum = -1 ;
  G__TFileEvioDictLN_TMemberInspector.tagnum = -1 ;
  G__TFileEvioDictLN_TObject.tagnum = -1 ;
  G__TFileEvioDictLN_TNamed.tagnum = -1 ;
  G__TFileEvioDictLN_vectorlEunsignedsPcharcOallocatorlEunsignedsPchargRsPgR.tagnum = -1 ;
  G__TFileEvioDictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR.tagnum = -1 ;
  G__TFileEvioDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__TFileEvioDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__TFileEvioDictLN_TBrowser.tagnum = -1 ;
  G__TFileEvioDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__TFileEvioDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__TFileEvioDictLN_TArrayC.tagnum = -1 ;
  G__TFileEvioDictLN_TVectorTlEfloatgR.tagnum = -1 ;
  G__TFileEvioDictLN_TVectorTlEdoublegR.tagnum = -1 ;
  G__TFileEvioDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR.tagnum = -1 ;
  G__TFileEvioDictLN_vectorlEstringcOallocatorlEstringgRsPgR.tagnum = -1 ;
  G__TFileEvioDictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__TFileEvioDictLN_vectorlEDescriptorEntry_tcOallocatorlEDescriptorEntry_tgRsPgR.tagnum = -1 ;
  G__TFileEvioDictLN_reverse_iteratorlEvectorlEDescriptorEntry_tcOallocatorlEDescriptorEntry_tgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__TFileEvioDictLN_maplEintcOvectorlEdoublecOallocatorlEdoublegRsPgRcOlesslEintgRcOallocatorlEpairlEconstsPintcOvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRsPgR.tagnum = -1 ;
  G__TFileEvioDictLN_vectorlEintcOallocatorlEintgRsPgR.tagnum = -1 ;
  G__TFileEvioDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__TFileEvioDictLN_maplEintcOvectorlEintcOallocatorlEintgRsPgRcOlesslEintgRcOallocatorlEpairlEconstsPintcOvectorlEintcOallocatorlEintgRsPgRsPgRsPgRsPgR.tagnum = -1 ;
  G__TFileEvioDictLN_vectorlECompositeADC_tcOallocatorlECompositeADC_tgRsPgR.tagnum = -1 ;
  G__TFileEvioDictLN_reverse_iteratorlEvectorlECompositeADC_tcOallocatorlECompositeADC_tgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__TFileEvioDictLN_maplEunsignedsPintcObankIndex_tcOlesslEunsignedsPintgRcOallocatorlEpairlEconstsPunsignedsPintcObankIndex_tgRsPgRsPgR.tagnum = -1 ;
  G__TFileEvioDictLN_vectorlETStringcOallocatorlETStringgRsPgR.tagnum = -1 ;
  G__TFileEvioDictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__TFileEvioDictLN_TFileEvio.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableTFileEvioDict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__TFileEvioDictLN_TClass);
   G__get_linked_tagnum_fwd(&G__TFileEvioDictLN_TBuffer);
   G__get_linked_tagnum_fwd(&G__TFileEvioDictLN_TDirectory);
   G__get_linked_tagnum_fwd(&G__TFileEvioDictLN_TMemberInspector);
   G__get_linked_tagnum_fwd(&G__TFileEvioDictLN_TObject);
   G__get_linked_tagnum_fwd(&G__TFileEvioDictLN_TNamed);
   G__get_linked_tagnum_fwd(&G__TFileEvioDictLN_vectorlEunsignedsPcharcOallocatorlEunsignedsPchargRsPgR);
   G__get_linked_tagnum_fwd(&G__TFileEvioDictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR);
   G__get_linked_tagnum_fwd(&G__TFileEvioDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__TFileEvioDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__TFileEvioDictLN_TBrowser);
   G__get_linked_tagnum_fwd(&G__TFileEvioDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__TFileEvioDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__TFileEvioDictLN_TArrayC);
   G__get_linked_tagnum_fwd(&G__TFileEvioDictLN_TVectorTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__TFileEvioDictLN_TVectorTlEdoublegR);
   G__get_linked_tagnum_fwd(&G__TFileEvioDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR);
   G__get_linked_tagnum_fwd(&G__TFileEvioDictLN_vectorlEstringcOallocatorlEstringgRsPgR);
   G__get_linked_tagnum_fwd(&G__TFileEvioDictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__TFileEvioDictLN_vectorlEDescriptorEntry_tcOallocatorlEDescriptorEntry_tgRsPgR);
   G__get_linked_tagnum_fwd(&G__TFileEvioDictLN_reverse_iteratorlEvectorlEDescriptorEntry_tcOallocatorlEDescriptorEntry_tgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__TFileEvioDictLN_maplEintcOvectorlEdoublecOallocatorlEdoublegRsPgRcOlesslEintgRcOallocatorlEpairlEconstsPintcOvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__TFileEvioDictLN_vectorlEintcOallocatorlEintgRsPgR);
   G__get_linked_tagnum_fwd(&G__TFileEvioDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__TFileEvioDictLN_maplEintcOvectorlEintcOallocatorlEintgRsPgRcOlesslEintgRcOallocatorlEpairlEconstsPintcOvectorlEintcOallocatorlEintgRsPgRsPgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__TFileEvioDictLN_vectorlECompositeADC_tcOallocatorlECompositeADC_tgRsPgR);
   G__get_linked_tagnum_fwd(&G__TFileEvioDictLN_reverse_iteratorlEvectorlECompositeADC_tcOallocatorlECompositeADC_tgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__TFileEvioDictLN_maplEunsignedsPintcObankIndex_tcOlesslEunsignedsPintgRcOallocatorlEpairlEconstsPunsignedsPintcObankIndex_tgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__TFileEvioDictLN_vectorlETStringcOallocatorlETStringgRsPgR);
   G__get_linked_tagnum_fwd(&G__TFileEvioDictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__TFileEvioDictLN_TFileEvio),sizeof(TFileEvio),-1,62720,(char*)NULL,G__setup_memvarTFileEvio,G__setup_memfuncTFileEvio);
}
extern "C" void G__cpp_setupTFileEvioDict(void) {
  G__check_setup_version(30051515,"G__cpp_setupTFileEvioDict()");
  G__set_cpp_environmentTFileEvioDict();
  G__cpp_setup_tagtableTFileEvioDict();

  G__cpp_setup_inheritanceTFileEvioDict();

  G__cpp_setup_typetableTFileEvioDict();

  G__cpp_setup_memvarTFileEvioDict();

  G__cpp_setup_memfuncTFileEvioDict();
  G__cpp_setup_globalTFileEvioDict();
  G__cpp_setup_funcTFileEvioDict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncTFileEvioDict();
  return;
}
class G__cpp_setup_initTFileEvioDict {
  public:
    G__cpp_setup_initTFileEvioDict() { G__add_setup_func("TFileEvioDict",(G__incsetup)(&G__cpp_setupTFileEvioDict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initTFileEvioDict() { G__remove_setup_func("TFileEvioDict"); }
};
G__cpp_setup_initTFileEvioDict G__cpp_setup_initializerTFileEvioDict;

