/********************************************************************
* src/root/TFileEvioDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error src/root/TFileEvioDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableTFileEvioDict();
extern void G__cpp_setup_inheritanceTFileEvioDict();
extern void G__cpp_setup_typetableTFileEvioDict();
extern void G__cpp_setup_memvarTFileEvioDict();
extern void G__cpp_setup_globalTFileEvioDict();
extern void G__cpp_setup_memfuncTFileEvioDict();
extern void G__cpp_setup_funcTFileEvioDict();
extern void G__set_cpp_environmentTFileEvioDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "src/root/TFileEvio.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__TFileEvioDictLN_TClass;
extern G__linked_taginfo G__TFileEvioDictLN_TBuffer;
extern G__linked_taginfo G__TFileEvioDictLN_TDirectory;
extern G__linked_taginfo G__TFileEvioDictLN_TMemberInspector;
extern G__linked_taginfo G__TFileEvioDictLN_TObject;
extern G__linked_taginfo G__TFileEvioDictLN_TNamed;
extern G__linked_taginfo G__TFileEvioDictLN_vectorlEunsignedsPcharcOallocatorlEunsignedsPchargRsPgR;
extern G__linked_taginfo G__TFileEvioDictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR;
extern G__linked_taginfo G__TFileEvioDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__TFileEvioDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TFileEvioDictLN_TBrowser;
extern G__linked_taginfo G__TFileEvioDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__TFileEvioDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TFileEvioDictLN_TArrayC;
extern G__linked_taginfo G__TFileEvioDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__TFileEvioDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__TFileEvioDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__TFileEvioDictLN_vectorlEstringcOallocatorlEstringgRsPgR;
extern G__linked_taginfo G__TFileEvioDictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TFileEvioDictLN_vectorlEDescriptorEntry_tcOallocatorlEDescriptorEntry_tgRsPgR;
extern G__linked_taginfo G__TFileEvioDictLN_reverse_iteratorlEvectorlEDescriptorEntry_tcOallocatorlEDescriptorEntry_tgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TFileEvioDictLN_maplEintcOvectorlEdoublecOallocatorlEdoublegRsPgRcOlesslEintgRcOallocatorlEpairlEconstsPintcOvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRsPgR;
extern G__linked_taginfo G__TFileEvioDictLN_vectorlEintcOallocatorlEintgRsPgR;
extern G__linked_taginfo G__TFileEvioDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TFileEvioDictLN_maplEintcOvectorlEintcOallocatorlEintgRsPgRcOlesslEintgRcOallocatorlEpairlEconstsPintcOvectorlEintcOallocatorlEintgRsPgRsPgRsPgRsPgR;
extern G__linked_taginfo G__TFileEvioDictLN_vectorlECompositeADC_tcOallocatorlECompositeADC_tgRsPgR;
extern G__linked_taginfo G__TFileEvioDictLN_reverse_iteratorlEvectorlECompositeADC_tcOallocatorlECompositeADC_tgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TFileEvioDictLN_vectorlETStringcOallocatorlETStringgRsPgR;
extern G__linked_taginfo G__TFileEvioDictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TFileEvioDictLN_TFileEvio;

/* STUB derived class for protected member access */
