//
// File generated by /opt/local/libexec/root5/bin/rootcint at Fri Sep 26 16:18:21 2014

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME srcdIrootdITTreeEvioDict
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "TTreeEvioDict.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TInterpreter.h"
#include "TVirtualMutex.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// Direct notice to TROOT of the dictionary's loading.
namespace {
   static struct DictInit {
      DictInit() {
         ROOT::RegisterModule();
      }
   } __TheDictionaryInitializer;
}

// START OF SHADOWS

namespace ROOT {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOT
// END OF SHADOWS

namespace ROOT {
   void TTreeEvio_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void *new_TTreeEvio(void *p = 0);
   static void *newArray_TTreeEvio(Long_t size, void *p);
   static void delete_TTreeEvio(void *p);
   static void deleteArray_TTreeEvio(void *p);
   static void destruct_TTreeEvio(void *p);
   static void directoryAutoAdd_TTreeEvio(void *obj, TDirectory *dir);
   static void streamer_TTreeEvio(TBuffer &buf, void *obj);
   static Long64_t merge_TTreeEvio(void *obj, TCollection *coll,TFileMergeInfo *info);
   static void reset_TTreeEvio(void *obj, TFileMergeInfo *info);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::TTreeEvio*)
   {
      ::TTreeEvio *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::TTreeEvio >(0);
      static ::ROOT::TGenericClassInfo 
         instance("TTreeEvio", ::TTreeEvio::Class_Version(), "./src/root/TTreeEvio.h", 29,
                  typeid(::TTreeEvio), DefineBehavior(ptr, ptr),
                  &::TTreeEvio::Dictionary, isa_proxy, 0,
                  sizeof(::TTreeEvio) );
      instance.SetNew(&new_TTreeEvio);
      instance.SetNewArray(&newArray_TTreeEvio);
      instance.SetDelete(&delete_TTreeEvio);
      instance.SetDeleteArray(&deleteArray_TTreeEvio);
      instance.SetDestructor(&destruct_TTreeEvio);
      instance.SetDirectoryAutoAdd(&directoryAutoAdd_TTreeEvio);
      instance.SetStreamerFunc(&streamer_TTreeEvio);
      instance.SetMerge(&merge_TTreeEvio);
      instance.SetResetAfterMerge(&reset_TTreeEvio);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::TTreeEvio*)
   {
      return GenerateInitInstanceLocal((::TTreeEvio*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::TTreeEvio*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOT

//______________________________________________________________________________
atomic_TClass_ptr TTreeEvio::fgIsA(0);  // static to hold class pointer

//______________________________________________________________________________
const char *TTreeEvio::Class_Name()
{
   return "TTreeEvio";
}

//______________________________________________________________________________
const char *TTreeEvio::ImplFileName()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::TTreeEvio*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int TTreeEvio::ImplFileLine()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::TTreeEvio*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void TTreeEvio::Dictionary()
{
   fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::TTreeEvio*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *TTreeEvio::Class()
{
   if (!fgIsA) { R__LOCKGUARD2(gCINTMutex); if(!fgIsA) {fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::TTreeEvio*)0x0)->GetClass();} }
   return fgIsA;
}

//______________________________________________________________________________
void TTreeEvio::Streamer(TBuffer &R__b)
{
   // Stream an object of class TTreeEvio.

   UInt_t R__s, R__c;
   if (R__b.IsReading()) {
      Version_t R__v = R__b.ReadVersion(&R__s, &R__c); if (R__v) { }
      TTree::Streamer(R__b);
      R__b >> variableD;
      R__b >> variableI;
      R__b >> valueI;
      bankEvnt.Streamer(R__b);
      R__b >> evioReader;
      R__b.CheckByteCount(R__s, R__c, TTreeEvio::IsA());
   } else {
      R__c = R__b.WriteVersion(TTreeEvio::IsA(), kTRUE);
      TTree::Streamer(R__b);
      R__b << variableD;
      R__b << variableI;
      R__b << valueI;
      bankEvnt.Streamer(R__b);
      R__b << evioReader;
      R__b.SetByteCount(R__c, kTRUE);
   }
}

//______________________________________________________________________________
void TTreeEvio::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class TTreeEvio.
      TClass *R__cl = ::TTreeEvio::IsA();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "variableD", &variableD);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "variableI", &variableI);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "valueI", &valueI);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "bankEvnt", &bankEvnt);
      R__insp.InspectMember(bankEvnt, "bankEvnt.");
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*evioReader", &evioReader);
      TTree::ShowMembers(R__insp);
}

namespace ROOT {
   // Wrappers around operator new
   static void *new_TTreeEvio(void *p) {
      return  p ? new(p) ::TTreeEvio : new ::TTreeEvio;
   }
   static void *newArray_TTreeEvio(Long_t nElements, void *p) {
      return p ? new(p) ::TTreeEvio[nElements] : new ::TTreeEvio[nElements];
   }
   // Wrapper around operator delete
   static void delete_TTreeEvio(void *p) {
      delete ((::TTreeEvio*)p);
   }
   static void deleteArray_TTreeEvio(void *p) {
      delete [] ((::TTreeEvio*)p);
   }
   static void destruct_TTreeEvio(void *p) {
      typedef ::TTreeEvio current_t;
      ((current_t*)p)->~current_t();
   }
   // Wrapper around the directory auto add.
   static void directoryAutoAdd_TTreeEvio(void *p, TDirectory *dir) {
      ((::TTreeEvio*)p)->DirectoryAutoAdd(dir);
   }
   // Wrapper around a custom streamer member function.
   static void streamer_TTreeEvio(TBuffer &buf, void *obj) {
      ((::TTreeEvio*)obj)->::TTreeEvio::Streamer(buf);
   }
   // Wrapper around the merge function.
   static Long64_t merge_TTreeEvio(void *obj,TCollection *coll,TFileMergeInfo *info) {
      return ((::TTreeEvio*)obj)->Merge(coll,info);
   }
   // Wrapper around the Reset function.
   static void reset_TTreeEvio(void *obj,TFileMergeInfo *info) {
      ((::TTreeEvio*)obj)->ResetAfterMerge(info);
   }
} // end of namespace ROOT for class ::TTreeEvio

/********************************************************
* src/root/TTreeEvioDict.cc
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtableTTreeEvioDict();

extern "C" void G__set_cpp_environmentTTreeEvioDict() {
  G__cpp_reset_tagtableTTreeEvioDict();
}
#include <new>
extern "C" int G__cpp_dllrevTTreeEvioDict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* TTreeEvio */
static int G__TTreeEvioDict_595_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   TTreeEvio* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new TTreeEvio[n];
     } else {
       p = new((void*) gvp) TTreeEvio[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new TTreeEvio;
     } else {
       p = new((void*) gvp) TTreeEvio;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__TTreeEvioDictLN_TTreeEvio));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TTreeEvioDict_595_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   TTreeEvio* p = NULL;
   char* gvp = (char*) G__getgvp();
   //m: 1
   if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
     p = new TTreeEvio((const char*) G__int(libp->para[0]));
   } else {
     p = new((void*) gvp) TTreeEvio((const char*) G__int(libp->para[0]));
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__TTreeEvioDictLN_TTreeEvio));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TTreeEvioDict_595_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TTreeEvio*) G__getstructoffset())->InitBranches();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TTreeEvioDict_595_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TTreeEvio*) G__getstructoffset())->InitBranch(*(TBankDescriptor*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TTreeEvioDict_595_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TTreeEvio*) G__getstructoffset())->InitDescriptors();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TTreeEvioDict_595_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) TTreeEvio::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TTreeEvioDict_595_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) TTreeEvio::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TTreeEvioDict_595_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) TTreeEvio::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TTreeEvioDict_595_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      TTreeEvio::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TTreeEvioDict_595_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TTreeEvio*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TTreeEvioDict_595_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) TTreeEvio::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TTreeEvioDict_595_0_20(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) TTreeEvio::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TTreeEvioDict_595_0_21(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) TTreeEvio::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TTreeEvioDict_595_0_22(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) TTreeEvio::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef TTreeEvio G__TTTreeEvio;
static int G__TTreeEvioDict_595_0_23(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (TTreeEvio*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((TTreeEvio*) (soff+(sizeof(TTreeEvio)*i)))->~G__TTTreeEvio();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (TTreeEvio*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((TTreeEvio*) (soff))->~G__TTTreeEvio();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* TTreeEvio */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncTTreeEvioDict {
 public:
  G__Sizep2memfuncTTreeEvioDict(): p(&G__Sizep2memfuncTTreeEvioDict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncTTreeEvioDict::*p)();
};

size_t G__get_sizep2memfuncTTreeEvioDict()
{
  G__Sizep2memfuncTTreeEvioDict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceTTreeEvioDict() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__TTreeEvioDictLN_TTreeEvio))) {
     TTreeEvio *G__Lderived;
     G__Lderived=(TTreeEvio*)0x1000;
     {
       TTree *G__Lpbase=(TTree*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__TTreeEvioDictLN_TTreeEvio),G__get_linked_tagnum(&G__TTreeEvioDictLN_TTree),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
     {
       TNamed *G__Lpbase=(TNamed*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__TTreeEvioDictLN_TTreeEvio),G__get_linked_tagnum(&G__TTreeEvioDictLN_TNamed),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__TTreeEvioDictLN_TTreeEvio),G__get_linked_tagnum(&G__TTreeEvioDictLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TAttLine *G__Lpbase=(TAttLine*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__TTreeEvioDictLN_TTreeEvio),G__get_linked_tagnum(&G__TTreeEvioDictLN_TAttLine),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TAttFill *G__Lpbase=(TAttFill*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__TTreeEvioDictLN_TTreeEvio),G__get_linked_tagnum(&G__TTreeEvioDictLN_TAttFill),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TAttMarker *G__Lpbase=(TAttMarker*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__TTreeEvioDictLN_TTreeEvio),G__get_linked_tagnum(&G__TTreeEvioDictLN_TAttMarker),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableTTreeEvioDict() {

   /* Setting up typedef entry */
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__TTreeEvioDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__TTreeEvioDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__TTreeEvioDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__TTreeEvioDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__TTreeEvioDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__TTreeEvioDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__TTreeEvioDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__TTreeEvioDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__TTreeEvioDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__TTreeEvioDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<std::bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__TTreeEvioDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__TTreeEvioDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*>",117,G__get_linked_tagnum(&G__TTreeEvioDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long>",117,G__get_linked_tagnum(&G__TTreeEvioDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long,const TObject**>",117,G__get_linked_tagnum(&G__TTreeEvioDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<std::string,TObjArray*>",117,G__get_linked_tagnum(&G__TTreeEvioDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*>",117,G__get_linked_tagnum(&G__TTreeEvioDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*>",117,G__get_linked_tagnum(&G__TTreeEvioDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*,less<string> >",117,G__get_linked_tagnum(&G__TTreeEvioDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Float_t>",117,G__get_linked_tagnum(&G__TTreeEvioDictLN_TVectorTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Double_t>",117,G__get_linked_tagnum(&G__TTreeEvioDictLN_TVectorTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<string>",117,G__get_linked_tagnum(&G__TTreeEvioDictLN_vectorlEstringcOallocatorlEstringgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__TTreeEvioDictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__TTreeEvioDictLN_vectorlEstringcOallocatorlEstringgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__TTreeEvioDictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__TTreeEvioDictLN_vectorlEstringcOallocatorlEstringgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<DescriptorEntry_t>",117,G__get_linked_tagnum(&G__TTreeEvioDictLN_vectorlEDescriptorEntry_tcOallocatorlEDescriptorEntry_tgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__TTreeEvioDictLN_reverse_iteratorlEvectorlEDescriptorEntry_tcOallocatorlEDescriptorEntry_tgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__TTreeEvioDictLN_vectorlEDescriptorEntry_tcOallocatorlEDescriptorEntry_tgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__TTreeEvioDictLN_reverse_iteratorlEvectorlEDescriptorEntry_tcOallocatorlEDescriptorEntry_tgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__TTreeEvioDictLN_vectorlEDescriptorEntry_tcOallocatorlEDescriptorEntry_tgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<int,vector<double> >",117,G__get_linked_tagnum(&G__TTreeEvioDictLN_maplEintcOvectorlEdoublecOallocatorlEdoublegRsPgRcOlesslEintgRcOallocatorlEpairlEconstsPintcOvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<int,vector<double,allocator<double> > >",117,G__get_linked_tagnum(&G__TTreeEvioDictLN_maplEintcOvectorlEdoublecOallocatorlEdoublegRsPgRcOlesslEintgRcOallocatorlEpairlEconstsPintcOvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<int,vector<double,allocator<double> >,less<int> >",117,G__get_linked_tagnum(&G__TTreeEvioDictLN_maplEintcOvectorlEdoublecOallocatorlEdoublegRsPgRcOlesslEintgRcOallocatorlEpairlEconstsPintcOvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<int32_t>",117,G__get_linked_tagnum(&G__TTreeEvioDictLN_vectorlEintcOallocatorlEintgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__TTreeEvioDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__TTreeEvioDictLN_vectorlEintcOallocatorlEintgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__TTreeEvioDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__TTreeEvioDictLN_vectorlEintcOallocatorlEintgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<int>",117,G__get_linked_tagnum(&G__TTreeEvioDictLN_vectorlEintcOallocatorlEintgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<int,vector<int32_t> >",117,G__get_linked_tagnum(&G__TTreeEvioDictLN_maplEintcOvectorlEintcOallocatorlEintgRsPgRcOlesslEintgRcOallocatorlEpairlEconstsPintcOvectorlEintcOallocatorlEintgRsPgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<int,vector<int,allocator<int> > >",117,G__get_linked_tagnum(&G__TTreeEvioDictLN_maplEintcOvectorlEintcOallocatorlEintgRsPgRcOlesslEintgRcOallocatorlEpairlEconstsPintcOvectorlEintcOallocatorlEintgRsPgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<int,vector<int,allocator<int> >,less<int> >",117,G__get_linked_tagnum(&G__TTreeEvioDictLN_maplEintcOvectorlEintcOallocatorlEintgRsPgRcOlesslEintgRcOallocatorlEpairlEconstsPintcOvectorlEintcOallocatorlEintgRsPgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<CompositeADC_t>",117,G__get_linked_tagnum(&G__TTreeEvioDictLN_vectorlECompositeADC_tcOallocatorlECompositeADC_tgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__TTreeEvioDictLN_reverse_iteratorlEvectorlECompositeADC_tcOallocatorlECompositeADC_tgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__TTreeEvioDictLN_vectorlECompositeADC_tcOallocatorlECompositeADC_tgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__TTreeEvioDictLN_reverse_iteratorlEvectorlECompositeADC_tcOallocatorlECompositeADC_tgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__TTreeEvioDictLN_vectorlECompositeADC_tcOallocatorlECompositeADC_tgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<uint32_t>",117,G__get_linked_tagnum(&G__TTreeEvioDictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<uint8_t>",117,G__get_linked_tagnum(&G__TTreeEvioDictLN_vectorlEunsignedsPcharcOallocatorlEunsignedsPchargRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<pair<int,int> >",117,G__get_linked_tagnum(&G__TTreeEvioDictLN_vectorlEpairlEintcOintgRcOallocatorlEpairlEintcOintgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__TTreeEvioDictLN_reverse_iteratorlEvectorlEpairlEintcOintgRcOallocatorlEpairlEintcOintgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__TTreeEvioDictLN_vectorlEpairlEintcOintgRcOallocatorlEpairlEintcOintgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__TTreeEvioDictLN_reverse_iteratorlEvectorlEpairlEintcOintgRcOallocatorlEpairlEintcOintgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__TTreeEvioDictLN_vectorlEpairlEintcOintgRcOallocatorlEpairlEintcOintgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<pair<string,string> >",117,G__get_linked_tagnum(&G__TTreeEvioDictLN_vectorlEpairlEstringcOstringgRcOallocatorlEpairlEstringcOstringgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__TTreeEvioDictLN_reverse_iteratorlEvectorlEpairlEstringcOstringgRcOallocatorlEpairlEstringcOstringgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__TTreeEvioDictLN_vectorlEpairlEstringcOstringgRcOallocatorlEpairlEstringcOstringgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__TTreeEvioDictLN_reverse_iteratorlEvectorlEpairlEstringcOstringgRcOallocatorlEpairlEstringcOstringgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__TTreeEvioDictLN_vectorlEpairlEstringcOstringgRcOallocatorlEpairlEstringcOstringgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* TTreeEvio */
static void G__setup_memvarTTreeEvio(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__TTreeEvioDictLN_TTreeEvio));
   { TTreeEvio *p; p=(TTreeEvio*)0x1000; if (p) { }
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"variableD=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,G__defined_typename("Int_t"),-1,4,"variableI=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,G__defined_typename("Int_t"),-1,4,"valueI=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__TTreeEvioDictLN_TBankDescriptor),-1,-1,4,"bankEvnt=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__TTreeEvioDictLN_EvioFileReader),-1,-1,4,"evioReader=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__TTreeEvioDictLN_TClass),G__defined_typename("atomic_TClass_ptr"),-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarTTreeEvioDict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncTTreeEvio(void) {
   /* TTreeEvio */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__TTreeEvioDictLN_TTreeEvio));
   G__memfunc_setup("TTreeEvio",887,G__TTreeEvioDict_595_0_1, 105, G__get_linked_tagnum(&G__TTreeEvioDictLN_TTreeEvio), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("TTreeEvio",887,G__TTreeEvioDict_595_0_2, 105, G__get_linked_tagnum(&G__TTreeEvioDictLN_TTreeEvio), -1, 0, 1, 1, 1, 0, "C - - 10 - filename", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetEntries",1018,(G__InterfaceMethod) NULL,110, -1, G__defined_typename("Long64_t"), 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("GetEntries",1018,(G__InterfaceMethod) NULL,110, -1, G__defined_typename("Long64_t"), 0, 1, 1, 1, 0, "C - - 10 - selection", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("GetEntriesFast",1416,(G__InterfaceMethod) NULL,110, -1, G__defined_typename("Long64_t"), 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("GetEntriesFriend",1618,(G__InterfaceMethod) NULL,110, -1, G__defined_typename("Long64_t"), 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("LoadTree",784,(G__InterfaceMethod) NULL,110, -1, G__defined_typename("Long64_t"), 0, 1, 1, 1, 0, "n - 'Long64_t' 0 - entry", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("InitBranches",1210,G__TTreeEvioDict_595_0_8, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("InitBranch",994,G__TTreeEvioDict_595_0_9, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBankDescriptor' - 1 - desc", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("InitDescriptors",1574,G__TTreeEvioDict_595_0_10, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Class",502,G__TTreeEvioDict_595_0_11, 85, G__get_linked_tagnum(&G__TTreeEvioDictLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&TTreeEvio::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__TTreeEvioDict_595_0_12, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&TTreeEvio::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__TTreeEvioDict_595_0_13, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&TTreeEvio::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__TTreeEvioDict_595_0_14, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&TTreeEvio::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__TTreeEvioDictLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__TTreeEvioDict_595_0_18, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - ClassDef_StreamerNVirtual_b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__TTreeEvioDict_595_0_19, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&TTreeEvio::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__TTreeEvioDict_595_0_20, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&TTreeEvio::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__TTreeEvioDict_595_0_21, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&TTreeEvio::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__TTreeEvioDict_595_0_22, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&TTreeEvio::DeclFileLine) ), 0);
   // automatic destructor
   G__memfunc_setup("~TTreeEvio", 1013, G__TTreeEvioDict_595_0_23, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncTTreeEvioDict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
}

static void G__cpp_setup_global2() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalTTreeEvioDict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {
}

static void G__cpp_setup_func16() {
}

static void G__cpp_setup_func17() {
}

static void G__cpp_setup_func18() {
}

static void G__cpp_setup_func19() {
}

static void G__cpp_setup_func20() {
}

static void G__cpp_setup_func21() {
}

static void G__cpp_setup_func22() {
}

static void G__cpp_setup_func23() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcTTreeEvioDict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
  G__cpp_setup_func16();
  G__cpp_setup_func17();
  G__cpp_setup_func18();
  G__cpp_setup_func19();
  G__cpp_setup_func20();
  G__cpp_setup_func21();
  G__cpp_setup_func22();
  G__cpp_setup_func23();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__TTreeEvioDictLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__TTreeEvioDictLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__TTreeEvioDictLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__TTreeEvioDictLN_TObject = { "TObject" , 99 , -1 };
G__linked_taginfo G__TTreeEvioDictLN_TNamed = { "TNamed" , 99 , -1 };
G__linked_taginfo G__TTreeEvioDictLN_vectorlEunsignedsPcharcOallocatorlEunsignedsPchargRsPgR = { "vector<unsigned char,allocator<unsigned char> >" , 99 , -1 };
G__linked_taginfo G__TTreeEvioDictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR = { "vector<unsigned int,allocator<unsigned int> >" , 99 , -1 };
G__linked_taginfo G__TTreeEvioDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__TTreeEvioDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__TTreeEvioDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__TTreeEvioDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__TTreeEvioDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR = { "iterator<bidirectional_iterator_tag,TObject*,long,const TObject**,const TObject*&>" , 115 , -1 };
G__linked_taginfo G__TTreeEvioDictLN_TAttFill = { "TAttFill" , 99 , -1 };
G__linked_taginfo G__TTreeEvioDictLN_TTree = { "TTree" , 99 , -1 };
G__linked_taginfo G__TTreeEvioDictLN_TAttLine = { "TAttLine" , 99 , -1 };
G__linked_taginfo G__TTreeEvioDictLN_TAttMarker = { "TAttMarker" , 99 , -1 };
G__linked_taginfo G__TTreeEvioDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR = { "map<string,TObjArray*,less<string>,allocator<pair<const string,TObjArray*> > >" , 99 , -1 };
G__linked_taginfo G__TTreeEvioDictLN_TVectorTlEfloatgR = { "TVectorT<float>" , 99 , -1 };
G__linked_taginfo G__TTreeEvioDictLN_TVectorTlEdoublegR = { "TVectorT<double>" , 99 , -1 };
G__linked_taginfo G__TTreeEvioDictLN_vectorlEstringcOallocatorlEstringgRsPgR = { "vector<string,allocator<string> >" , 99 , -1 };
G__linked_taginfo G__TTreeEvioDictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<string,allocator<string> >::iterator>" , 99 , -1 };
G__linked_taginfo G__TTreeEvioDictLN_vectorlEDescriptorEntry_tcOallocatorlEDescriptorEntry_tgRsPgR = { "vector<DescriptorEntry_t,allocator<DescriptorEntry_t> >" , 99 , -1 };
G__linked_taginfo G__TTreeEvioDictLN_reverse_iteratorlEvectorlEDescriptorEntry_tcOallocatorlEDescriptorEntry_tgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<DescriptorEntry_t,allocator<DescriptorEntry_t> >::iterator>" , 99 , -1 };
G__linked_taginfo G__TTreeEvioDictLN_maplEintcOvectorlEdoublecOallocatorlEdoublegRsPgRcOlesslEintgRcOallocatorlEpairlEconstsPintcOvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRsPgR = { "map<int,vector<double,allocator<double> >,less<int>,allocator<pair<const int,vector<double,allocator<double> > > > >" , 99 , -1 };
G__linked_taginfo G__TTreeEvioDictLN_vectorlEintcOallocatorlEintgRsPgR = { "vector<int,allocator<int> >" , 99 , -1 };
G__linked_taginfo G__TTreeEvioDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<int,allocator<int> >::iterator>" , 99 , -1 };
G__linked_taginfo G__TTreeEvioDictLN_maplEintcOvectorlEintcOallocatorlEintgRsPgRcOlesslEintgRcOallocatorlEpairlEconstsPintcOvectorlEintcOallocatorlEintgRsPgRsPgRsPgRsPgR = { "map<int,vector<int,allocator<int> >,less<int>,allocator<pair<const int,vector<int,allocator<int> > > > >" , 99 , -1 };
G__linked_taginfo G__TTreeEvioDictLN_vectorlECompositeADC_tcOallocatorlECompositeADC_tgRsPgR = { "vector<CompositeADC_t,allocator<CompositeADC_t> >" , 99 , -1 };
G__linked_taginfo G__TTreeEvioDictLN_reverse_iteratorlEvectorlECompositeADC_tcOallocatorlECompositeADC_tgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<CompositeADC_t,allocator<CompositeADC_t> >::iterator>" , 99 , -1 };
G__linked_taginfo G__TTreeEvioDictLN_EvioFileReader = { "EvioFileReader" , 99 , -1 };
G__linked_taginfo G__TTreeEvioDictLN_TBankDescriptor = { "TBankDescriptor" , 99 , -1 };
G__linked_taginfo G__TTreeEvioDictLN_vectorlEpairlEintcOintgRcOallocatorlEpairlEintcOintgRsPgRsPgR = { "vector<pair<int,int>,allocator<pair<int,int> > >" , 99 , -1 };
G__linked_taginfo G__TTreeEvioDictLN_reverse_iteratorlEvectorlEpairlEintcOintgRcOallocatorlEpairlEintcOintgRsPgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<pair<int,int>,allocator<pair<int,int> > >::iterator>" , 99 , -1 };
G__linked_taginfo G__TTreeEvioDictLN_vectorlEpairlEstringcOstringgRcOallocatorlEpairlEstringcOstringgRsPgRsPgR = { "vector<pair<string,string>,allocator<pair<string,string> > >" , 99 , -1 };
G__linked_taginfo G__TTreeEvioDictLN_reverse_iteratorlEvectorlEpairlEstringcOstringgRcOallocatorlEpairlEstringcOstringgRsPgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<pair<string,string>,allocator<pair<string,string> > >::iterator>" , 99 , -1 };
G__linked_taginfo G__TTreeEvioDictLN_TTreeEvio = { "TTreeEvio" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableTTreeEvioDict() {
  G__TTreeEvioDictLN_TClass.tagnum = -1 ;
  G__TTreeEvioDictLN_TBuffer.tagnum = -1 ;
  G__TTreeEvioDictLN_TMemberInspector.tagnum = -1 ;
  G__TTreeEvioDictLN_TObject.tagnum = -1 ;
  G__TTreeEvioDictLN_TNamed.tagnum = -1 ;
  G__TTreeEvioDictLN_vectorlEunsignedsPcharcOallocatorlEunsignedsPchargRsPgR.tagnum = -1 ;
  G__TTreeEvioDictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR.tagnum = -1 ;
  G__TTreeEvioDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__TTreeEvioDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__TTreeEvioDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__TTreeEvioDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__TTreeEvioDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR.tagnum = -1 ;
  G__TTreeEvioDictLN_TAttFill.tagnum = -1 ;
  G__TTreeEvioDictLN_TTree.tagnum = -1 ;
  G__TTreeEvioDictLN_TAttLine.tagnum = -1 ;
  G__TTreeEvioDictLN_TAttMarker.tagnum = -1 ;
  G__TTreeEvioDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR.tagnum = -1 ;
  G__TTreeEvioDictLN_TVectorTlEfloatgR.tagnum = -1 ;
  G__TTreeEvioDictLN_TVectorTlEdoublegR.tagnum = -1 ;
  G__TTreeEvioDictLN_vectorlEstringcOallocatorlEstringgRsPgR.tagnum = -1 ;
  G__TTreeEvioDictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__TTreeEvioDictLN_vectorlEDescriptorEntry_tcOallocatorlEDescriptorEntry_tgRsPgR.tagnum = -1 ;
  G__TTreeEvioDictLN_reverse_iteratorlEvectorlEDescriptorEntry_tcOallocatorlEDescriptorEntry_tgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__TTreeEvioDictLN_maplEintcOvectorlEdoublecOallocatorlEdoublegRsPgRcOlesslEintgRcOallocatorlEpairlEconstsPintcOvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRsPgR.tagnum = -1 ;
  G__TTreeEvioDictLN_vectorlEintcOallocatorlEintgRsPgR.tagnum = -1 ;
  G__TTreeEvioDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__TTreeEvioDictLN_maplEintcOvectorlEintcOallocatorlEintgRsPgRcOlesslEintgRcOallocatorlEpairlEconstsPintcOvectorlEintcOallocatorlEintgRsPgRsPgRsPgRsPgR.tagnum = -1 ;
  G__TTreeEvioDictLN_vectorlECompositeADC_tcOallocatorlECompositeADC_tgRsPgR.tagnum = -1 ;
  G__TTreeEvioDictLN_reverse_iteratorlEvectorlECompositeADC_tcOallocatorlECompositeADC_tgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__TTreeEvioDictLN_EvioFileReader.tagnum = -1 ;
  G__TTreeEvioDictLN_TBankDescriptor.tagnum = -1 ;
  G__TTreeEvioDictLN_vectorlEpairlEintcOintgRcOallocatorlEpairlEintcOintgRsPgRsPgR.tagnum = -1 ;
  G__TTreeEvioDictLN_reverse_iteratorlEvectorlEpairlEintcOintgRcOallocatorlEpairlEintcOintgRsPgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__TTreeEvioDictLN_vectorlEpairlEstringcOstringgRcOallocatorlEpairlEstringcOstringgRsPgRsPgR.tagnum = -1 ;
  G__TTreeEvioDictLN_reverse_iteratorlEvectorlEpairlEstringcOstringgRcOallocatorlEpairlEstringcOstringgRsPgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__TTreeEvioDictLN_TTreeEvio.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableTTreeEvioDict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__TTreeEvioDictLN_TClass);
   G__get_linked_tagnum_fwd(&G__TTreeEvioDictLN_TBuffer);
   G__get_linked_tagnum_fwd(&G__TTreeEvioDictLN_TMemberInspector);
   G__get_linked_tagnum_fwd(&G__TTreeEvioDictLN_TObject);
   G__get_linked_tagnum_fwd(&G__TTreeEvioDictLN_TNamed);
   G__get_linked_tagnum_fwd(&G__TTreeEvioDictLN_vectorlEunsignedsPcharcOallocatorlEunsignedsPchargRsPgR);
   G__get_linked_tagnum_fwd(&G__TTreeEvioDictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR);
   G__get_linked_tagnum_fwd(&G__TTreeEvioDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__TTreeEvioDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__TTreeEvioDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__TTreeEvioDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__TTreeEvioDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR);
   G__get_linked_tagnum_fwd(&G__TTreeEvioDictLN_TAttFill);
   G__get_linked_tagnum_fwd(&G__TTreeEvioDictLN_TTree);
   G__get_linked_tagnum_fwd(&G__TTreeEvioDictLN_TAttLine);
   G__get_linked_tagnum_fwd(&G__TTreeEvioDictLN_TAttMarker);
   G__get_linked_tagnum_fwd(&G__TTreeEvioDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__TTreeEvioDictLN_TVectorTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__TTreeEvioDictLN_TVectorTlEdoublegR);
   G__get_linked_tagnum_fwd(&G__TTreeEvioDictLN_vectorlEstringcOallocatorlEstringgRsPgR);
   G__get_linked_tagnum_fwd(&G__TTreeEvioDictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__TTreeEvioDictLN_vectorlEDescriptorEntry_tcOallocatorlEDescriptorEntry_tgRsPgR);
   G__get_linked_tagnum_fwd(&G__TTreeEvioDictLN_reverse_iteratorlEvectorlEDescriptorEntry_tcOallocatorlEDescriptorEntry_tgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__TTreeEvioDictLN_maplEintcOvectorlEdoublecOallocatorlEdoublegRsPgRcOlesslEintgRcOallocatorlEpairlEconstsPintcOvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__TTreeEvioDictLN_vectorlEintcOallocatorlEintgRsPgR);
   G__get_linked_tagnum_fwd(&G__TTreeEvioDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__TTreeEvioDictLN_maplEintcOvectorlEintcOallocatorlEintgRsPgRcOlesslEintgRcOallocatorlEpairlEconstsPintcOvectorlEintcOallocatorlEintgRsPgRsPgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__TTreeEvioDictLN_vectorlECompositeADC_tcOallocatorlECompositeADC_tgRsPgR);
   G__get_linked_tagnum_fwd(&G__TTreeEvioDictLN_reverse_iteratorlEvectorlECompositeADC_tcOallocatorlECompositeADC_tgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__TTreeEvioDictLN_EvioFileReader);
   G__get_linked_tagnum_fwd(&G__TTreeEvioDictLN_TBankDescriptor);
   G__get_linked_tagnum_fwd(&G__TTreeEvioDictLN_vectorlEpairlEintcOintgRcOallocatorlEpairlEintcOintgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__TTreeEvioDictLN_reverse_iteratorlEvectorlEpairlEintcOintgRcOallocatorlEpairlEintcOintgRsPgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__TTreeEvioDictLN_vectorlEpairlEstringcOstringgRcOallocatorlEpairlEstringcOstringgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__TTreeEvioDictLN_reverse_iteratorlEvectorlEpairlEstringcOstringgRcOallocatorlEpairlEstringcOstringgRsPgRsPgRcLcLiteratorgR);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__TTreeEvioDictLN_TTreeEvio),sizeof(TTreeEvio),-1,62720,(char*)NULL,G__setup_memvarTTreeEvio,G__setup_memfuncTTreeEvio);
}
extern "C" void G__cpp_setupTTreeEvioDict(void) {
  G__check_setup_version(30051515,"G__cpp_setupTTreeEvioDict()");
  G__set_cpp_environmentTTreeEvioDict();
  G__cpp_setup_tagtableTTreeEvioDict();

  G__cpp_setup_inheritanceTTreeEvioDict();

  G__cpp_setup_typetableTTreeEvioDict();

  G__cpp_setup_memvarTTreeEvioDict();

  G__cpp_setup_memfuncTTreeEvioDict();
  G__cpp_setup_globalTTreeEvioDict();
  G__cpp_setup_funcTTreeEvioDict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncTTreeEvioDict();
  return;
}
class G__cpp_setup_initTTreeEvioDict {
  public:
    G__cpp_setup_initTTreeEvioDict() { G__add_setup_func("TTreeEvioDict",(G__incsetup)(&G__cpp_setupTTreeEvioDict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initTTreeEvioDict() { G__remove_setup_func("TTreeEvioDict"); }
};
G__cpp_setup_initTTreeEvioDict G__cpp_setup_initializerTTreeEvioDict;

