/**
* Autogenerated Header File for TTreeEvio
* \\file TTreeEvio.h
* \\author G.Gavalian
* \\date 2014-09-25
*/
#ifndef __TTREEEVIO__
#define __TTREEEVIO__
#include <iostream>
#include <string>
#include <cmath>
#include <vector>
#include "TTree.h"
#include "TROOT.h"
#include "TBasket.h"
#include "TLeafI.h"
#include "TLeafD.h"
#include "TLeafF.h"
#include "TH1D.h"
#include "TDirectory.h"
#include "EvioFileReader.h"
#include "TBankDescriptor.h"
#include "TList.h"
#include "TXMLBankDictionary.h"

 
using namespace std;
//! A Brief Description
/*
 * A detailed description
 */
class TTreeEvio  : public TTree {

private:

  bool      kDebugMode;
  
  Double_t  variableD;
  Int_t     variableI;
  Int_t     valueI;
  Int_t     bankLengthEVNT;



  TBankDescriptor   bankEvnt;
  EvioFileReader *evioReader;

  TList             bankList;
  vector<int>       bankSizes;

public:

/** Default Constructor */

TTreeEvio();
TTreeEvio(const char *filename, bool debug = false);
TTreeEvio(const char *filename, const char *mode);

/** Default Destructor */
~TTreeEvio();
/** Copy Constructor if one is needed */
/*TTreeEvio( const TTreeEvio &obj); */ 
 //Long64_t Draw(const char* varexp, const char* selection, Option_t* option = "", Long64_t nentries = 1000000000, Long64_t firstentry = 0);
/** An operator = if one is needed */
/* const TTreeEvio &operator=(const TTreeEvio &obj); */

void        TestLoop(int nentries);

Long64_t    GetEntries() const;
Long64_t    GetEntries(const char* selection);
Long64_t    GetEntriesFast() const;
Long64_t    GetEntriesFriend() const;
Long64_t    LoadTree(Long64_t entry);

Int_t       GetNRows(const char *branch);
Double_t    GetValue(int row, const char *branch, const char *leaf);
Int_t       GetValueI(int row,const char *branch, const char *leaf);
Float_t     GetValueF(int row,const char *branch, const char *leaf);
Double_t    GetValueD(int row,const char *branch, const char *leaf);

void        InitBranches();
void        LoadBranches();
void        LoadBranch(TBankDescriptor &desc, int entry);
void        LoadDictionary();
void        LoadDictionary6();
void        InitBranch(TBankDescriptor &desc);
void        InitDescriptors();

 ClassDef(TTreeEvio,1)

};
#endif
