/********************************************************************
* src/root/TTreeEvioDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error src/root/TTreeEvioDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableTTreeEvioDict();
extern void G__cpp_setup_inheritanceTTreeEvioDict();
extern void G__cpp_setup_typetableTTreeEvioDict();
extern void G__cpp_setup_memvarTTreeEvioDict();
extern void G__cpp_setup_globalTTreeEvioDict();
extern void G__cpp_setup_memfuncTTreeEvioDict();
extern void G__cpp_setup_funcTTreeEvioDict();
extern void G__set_cpp_environmentTTreeEvioDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "src/root/TTreeEvio.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__TTreeEvioDictLN_TClass;
extern G__linked_taginfo G__TTreeEvioDictLN_TBuffer;
extern G__linked_taginfo G__TTreeEvioDictLN_TMemberInspector;
extern G__linked_taginfo G__TTreeEvioDictLN_TObject;
extern G__linked_taginfo G__TTreeEvioDictLN_TNamed;
extern G__linked_taginfo G__TTreeEvioDictLN_vectorlEunsignedsPcharcOallocatorlEunsignedsPchargRsPgR;
extern G__linked_taginfo G__TTreeEvioDictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR;
extern G__linked_taginfo G__TTreeEvioDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__TTreeEvioDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TTreeEvioDictLN_TList;
extern G__linked_taginfo G__TTreeEvioDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__TTreeEvioDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TTreeEvioDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__TTreeEvioDictLN_TAttFill;
extern G__linked_taginfo G__TTreeEvioDictLN_TTree;
extern G__linked_taginfo G__TTreeEvioDictLN_TAttLine;
extern G__linked_taginfo G__TTreeEvioDictLN_TAttMarker;
extern G__linked_taginfo G__TTreeEvioDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__TTreeEvioDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__TTreeEvioDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__TTreeEvioDictLN_vectorlEstringcOallocatorlEstringgRsPgR;
extern G__linked_taginfo G__TTreeEvioDictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TTreeEvioDictLN_vectorlEDescriptorEntry_tcOallocatorlEDescriptorEntry_tgRsPgR;
extern G__linked_taginfo G__TTreeEvioDictLN_reverse_iteratorlEvectorlEDescriptorEntry_tcOallocatorlEDescriptorEntry_tgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TTreeEvioDictLN_maplEintcOvectorlEdoublecOallocatorlEdoublegRsPgRcOlesslEintgRcOallocatorlEpairlEconstsPintcOvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRsPgR;
extern G__linked_taginfo G__TTreeEvioDictLN_vectorlEintcOallocatorlEintgRsPgR;
extern G__linked_taginfo G__TTreeEvioDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TTreeEvioDictLN_maplEintcOvectorlEintcOallocatorlEintgRsPgRcOlesslEintgRcOallocatorlEpairlEconstsPintcOvectorlEintcOallocatorlEintgRsPgRsPgRsPgRsPgR;
extern G__linked_taginfo G__TTreeEvioDictLN_vectorlECompositeADC_tcOallocatorlECompositeADC_tgRsPgR;
extern G__linked_taginfo G__TTreeEvioDictLN_reverse_iteratorlEvectorlECompositeADC_tcOallocatorlECompositeADC_tgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TTreeEvioDictLN_maplEunsignedsPintcObankIndex_tcOlesslEunsignedsPintgRcOallocatorlEpairlEconstsPunsignedsPintcObankIndex_tgRsPgRsPgR;
extern G__linked_taginfo G__TTreeEvioDictLN_EvioFileReader;
extern G__linked_taginfo G__TTreeEvioDictLN_TBankDescriptor;
extern G__linked_taginfo G__TTreeEvioDictLN_vectorlEpairlEintcOintgRcOallocatorlEpairlEintcOintgRsPgRsPgR;
extern G__linked_taginfo G__TTreeEvioDictLN_reverse_iteratorlEvectorlEpairlEintcOintgRcOallocatorlEpairlEintcOintgRsPgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TTreeEvioDictLN_vectorlEpairlEstringcOstringgRcOallocatorlEpairlEstringcOstringgRsPgRsPgR;
extern G__linked_taginfo G__TTreeEvioDictLN_reverse_iteratorlEvectorlEpairlEstringcOstringgRcOallocatorlEpairlEstringcOstringgRsPgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TTreeEvioDictLN_vectorlETStringcOallocatorlETStringgRsPgR;
extern G__linked_taginfo G__TTreeEvioDictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TTreeEvioDictLN_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgR;
extern G__linked_taginfo G__TTreeEvioDictLN_TTreeEvio;

/* STUB derived class for protected member access */
