/**
* Autogenerated Header File for TXMLBankDisctionary
* \\file TXMLBankDisctionary.h
* \\author G.Gavalian
* \\date 2014-09-29
*/
#ifndef __TXMLBANKDICTIONARY__
#define __TXMLBANKDICTIONARY__
#include <iostream>
#include <string>
#include <cmath>
#include <map>
#include <vector>
#include "TROOT.h"
#include "TList.h"
#include "TObject.h"
#include "TXMLEngine.h"
#include "TSystem.h"
#include "TBankDescriptor.h"
#include <stdio.h>
#include <stdlib.h>

using namespace std;
//! A Brief Description
/*
 * A detailed description
 */
class TXMLBankDictionary  {

private:
	
	TList bankDictionary;
	map<string,string>   getNodeAttributes(TXMLEngine* xml, XMLNodePointer_t node);

public:

/** Default Constructor */
TXMLBankDictionary();
/** Default Destructor */
~TXMLBankDictionary();
/** Copy Constructor if one is needed */
/*TXMLBankDisctionary( const TXMLBankDisctionary &obj); */ 
void  ParseFile(const char *env, const char *xmlfile);
void  ParseFile(const char *xmlFile);
/** An operator = if one is needed */
/* const TXMLBankDisctionary &operator=(const TXMLBankDisctionary &obj); */

void ParseBank(TXMLEngine* xml, XMLNodePointer_t bankNode);
void ParseSection(TXMLEngine* xml, XMLNodePointer_t sectionNode, const char *bankname);
TList    &GetList();

};
#endif
