/**
 * Autogenerated Header File for TEvioFileReader
 * \\file TEvioFileReader.h
 * \\author G.Gavalian
 * \\date 2012-07-14
 */

#ifndef __EVIODATAEVENT__
#define __EVIODATAEVENT__

#include <iostream>
#include <string>
#include <cmath>
#include <vector>
#include <map>
#include "EvioDataBank.h"
#include "common_std.h"

#ifndef MAXEVIOBUFFER
#define MAXEVIOBUFFER   4000000
#endif

using namespace std;

//using namespace evio;
//! A Brief Description
/*
 * A detailed description
 */

class EvioDataEvent {

private:

  uint32_t buffer[MAXEVIOBUFFER];

public:

  EvioDataEvent();
  EvioDataEvent(uint32_t *ptr, int len);
  EvioDataEvent(const EvioDataEvent& orig);
  ~EvioDataEvent();

  void init(uint32_t *ptr, int len);
  
  vector<double>  *getDoubleVector(int tag, int num);
  vector<int32_t> *getIntegerVector(int tag, int num);
  
  void getBank(EvioDataBank &bank, int tag, int num = 0);
  
};
#endif
