/**
 * Autogenerated Header File for TEvioFileReader
 * \\file TEvioFileReader.h
 * \\author G.Gavalian
 * \\date 2012-07-14
 */

#ifndef __EVIODATAEVENT__
#define __EVIODATAEVENT__

#include <iostream>
#include <string>
#include <cmath>
#include <vector>
#include <map>
#include "EvioDataBank.h"
#include "EvioCompositeDecoder.h"
#include "common_std.h"

#ifndef MAXEVIOBUFFER
#define MAXEVIOBUFFER   4000000
#endif

using namespace std;

//using namespace evio;
//! A Brief Description
/*
 * A detailed description
 */

class EvioDataEvent {

private:

  uint32_t buffer[MAXEVIOBUFFER];

public:

  EvioDataEvent();
  EvioDataEvent(uint32_t *ptr, int len);
  EvioDataEvent(const EvioDataEvent& orig);
  ~EvioDataEvent();

  void init(uint32_t *ptr, int len);
  
  vector<float>   *getFloatVector(int tag, int num);
  vector<double>  *getDoubleVector(int tag, int num);
  vector<int32_t> *getIntegerVector(int tag, int num);  
  void getBank(EvioDataBank &bank, int tag, int num = 0);
  void getList();
  vector<CompositeADC_t>  getCompositeData(int tag, int num);
  uint8_t          getInt8 (char *data, int offset);
  uint16_t         getInt16(char *data, int offset);
  uint32_t         getInt32(char *data, int offset);
   int64_t         getInt64(char *data, int offset);
  void             decodeCompositeData(char *data, int size);
};
#endif
