/**
* Autogenerated Header File for TEventOperation
* \\file TEventOperation.h
* \\author G.Gavalian
* \\date 2013-10-28
*/
#ifndef __TEVENTOPERATION__
#define __TEVENTOPERATION__
#include <iostream>
#include <string>
#include <cmath>
#include <vector>
#include "TROOT.h"
#include "TObject.h"
#include "TParticle.h"
#include "TLorentzVector.h"
#include "stdlib.h"

using namespace std;
//! A Brief Description
/*
 * A detailed description
 */
class TEventOperation  {

private:

  vector<int> operSigns;
  vector<int> operPids;
  vector<int> operOrders;
  TParticle   operParticle;

  
  vector<string> stringTokenize(const string &_str,const string &_delim);
  vector<string> expressionTokenize(const string &_str);
public:

/** Default Constructor */
TEventOperation();
/** Default Destructor */
~TEventOperation();
/** Copy Constructor if one is needed */
/*TEventOperation( const TEventOperation &obj); */ 
 void Clear();
 void AddOperand(int sign, int pid, int order);
 vector<int> &GetSigns(){ return operSigns;};
 vector<int> &GetPids() { return operPids;};
 vector<int> &GetOrders(){ return operOrders;};

 TLorentzVector  getVector();
 void       Print();
 void       PrintParticle();
 void       Parse(const char *operation);
 TParticle *GetParticle() { return &operParticle;};
 double     Mass();
 double     Mass2();
 double     Theta();
 double     Phi();
 double     P();
/** An operator = if one is needed */
/* const TEventOperation &operator=(const TEventOperation &obj); */
 
 ClassDef(TEventOperation,1)
};
#endif
