/********************************************************************
* src/tools/TPhysicsEventDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error src/tools/TPhysicsEventDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableTPhysicsEventDict();
extern void G__cpp_setup_inheritanceTPhysicsEventDict();
extern void G__cpp_setup_typetableTPhysicsEventDict();
extern void G__cpp_setup_memvarTPhysicsEventDict();
extern void G__cpp_setup_globalTPhysicsEventDict();
extern void G__cpp_setup_memfuncTPhysicsEventDict();
extern void G__cpp_setup_funcTPhysicsEventDict();
extern void G__set_cpp_environmentTPhysicsEventDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "src/tools/TPhysicsEvent.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__TPhysicsEventDictLN_TClass;
extern G__linked_taginfo G__TPhysicsEventDictLN_TBuffer;
extern G__linked_taginfo G__TPhysicsEventDictLN_TMemberInspector;
extern G__linked_taginfo G__TPhysicsEventDictLN_TObject;
extern G__linked_taginfo G__TPhysicsEventDictLN_TString;
extern G__linked_taginfo G__TPhysicsEventDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__TPhysicsEventDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TPhysicsEventDictLN_TObjArray;
extern G__linked_taginfo G__TPhysicsEventDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__TPhysicsEventDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TPhysicsEventDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__TPhysicsEventDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__TPhysicsEventDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__TPhysicsEventDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__TPhysicsEventDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__TPhysicsEventDictLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__TPhysicsEventDictLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__TPhysicsEventDictLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__TPhysicsEventDictLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__TPhysicsEventDictLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__TPhysicsEventDictLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__TPhysicsEventDictLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__TPhysicsEventDictLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__TPhysicsEventDictLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__TPhysicsEventDictLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__TPhysicsEventDictLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__TPhysicsEventDictLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__TPhysicsEventDictLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__TPhysicsEventDictLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__TPhysicsEventDictLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__TPhysicsEventDictLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__TPhysicsEventDictLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__TPhysicsEventDictLN_TLorentzVector;
extern G__linked_taginfo G__TPhysicsEventDictLN_TParticle;
extern G__linked_taginfo G__TPhysicsEventDictLN_TEventOperation;
extern G__linked_taginfo G__TPhysicsEventDictLN_vectorlEintcOallocatorlEintgRsPgR;
extern G__linked_taginfo G__TPhysicsEventDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TPhysicsEventDictLN_vectorlEstringcOallocatorlEstringgRsPgR;
extern G__linked_taginfo G__TPhysicsEventDictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TPhysicsEventDictLN_TPhysicsEvent;

/* STUB derived class for protected member access */
